### ISSUE TITLE
knop ‘resultaat weergeven’ bij zoeken is niet helder.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#1]
Wanneer staat ie nou uit of aan? Bij ‘aan’ wordt ie grijs? Rare kleurkeuze, bovendien heeft de knop bij annotatie’s een andere kleur.

**Comment by CoraPU** [comment]
-de knop Resultaat weergeven is inderdaad niet duidelijk aan lijkt uit ? Kleur blauw en grijs omdraaien ?
-bij aanzetten knop resultaatweergeven klappen ook de annotaties open in de inhoudsopgave wordt het erg onoverzichtelijk van.

**Comment by AnkeVanBeek-IDgis** [comment]
kleuren verschillende sliders gelijk getrokken. Grijs bij niet actief, blauw bij actief.

**Comment by CoraPU** [comment]
is aangepast
