### ISSUE TITLE
Kaartbeeld inzoomen op extent van gekozen regeling(en) cq ambtsgebied van organisatie

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#10]

**Comment by TitiaBaeten** [comment]
Werkt bij het opstarten van het eerste plan. Als je daarna een ander plan selecteert blijft deze op het vorige plan ingezoomd.

**Comment by copierrj** [comment]
Het is op dit moment zo geïmplementeerd dat het veranderen van plan (lees: het reeds actieve plan deactiveren en een ander plan daarvoor in de plaats aanzetten) resulteert in het inzoomen naar het nieuwe plan. Een additioneel plan aanzetten (dus het reeds actieve plan blijft actief) blijft het inzoomen achterwege vanuit de gedachten dat de gebruiker met het aanzetten van een extra plan waarschijnlijk aanvullende informatie wil opvragen bij de huidige locatie.

**Comment by HermanAssink** [comment]
Goede oplossing
