### ISSUE TITLE
Visie hoofdkopje regeling aanpassen

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#106]
De ingeladen visie van ons heeft als hoofdkopje "regeling" ik vind dat niet zo passend.

En ook later het kopje "bijlagen bij regeling"

Ik zou daar misschien eerder Omgevingsvisie van maken.. Of als dat generieker moet: Document of beleidsdocument oid...

**Comment by lamerise** [comment]
misschien ook kijken of we het kopje opschrift nodig hebben.. Ook bij een visie is dat een beetje vreemde...

**Comment by HermanAssink** [comment]
I.p.v. "regeling" het type instrument (Omgevingsvisie, Omgevingsverordening, Omgevingsplan, e.d.) als kopje gebruiken, idem bij "bijlagen bij regeling"

**Comment by MaxIDgis** [comment]
Aangezien het type instrument al in de titel boven de inhoudsopgave staat is het misschien dubbelop om dan het type instrument ook weer als kopje in de inhoudsopgave te hebben.

Een  andere mogelijke oplossing om van het kopje regeling af te stappen is om dat kopje helemaal weg te laten. Dan komt de inhoud van het document gelijk in de inhoudsopgave zonder eerst door het kopje regeling (of hoe het anders ook zou heten) te moeten klikken. We kunnen de "bijlagen bij regeling" dan ook hernoemen naar "bijlagen".

Om nog steeds alle inhoud in een document in een keer te kunnen selecteren kunnen we een knopje "Alles selecteren" toevoegen net zoals we al een knopje "Alles uitzetten" hebben. Alles selecteren en alles uitzetten zou ook een enkel knopje kunnen worden.

Dus nu is de inhoudsopgave:
- Regeling
  - Hoofdstuk 1
  - Hoofdstuk 2
  ...
- Bijlagen bij regeling
  - ...

etc.

De alternatieve oplossing:
- Hoofdstuk 1
- Hoofdstuk 2
...
- Bijlagen
  - ...

etc.

**Comment by lamerise** [comment]
laat dan toch maar regeling, anders krijgen we weer een extra knopje in de interface om alles aan te zetten

**Comment by lamerise** [comment]
Kan je bij visies en programma de tekst regeling nog aanpassen in beleid of beleidstekst of beleidsdocument

**Comment by MaxIDgis** [comment]
Dit is hetzelfde als issue https://github.com/IDgis/PlanoView2-bevindingen/issues/113
