### ISSUE TITLE
type hoofdlijn gebruiken om het zoeken op hoofdlijnen de structureren

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#108]
Als het goed is zouden er subtypen van hoofdlijnen in moeten zitten.

Graag de zoekopties ordenen via die lijn

**Comment by lamerise** [comment]
![image](https://user-images.githubusercontent.com/114915209/216543855-2a405178-3ac3-4c90-947a-6cbdcb82b48d.png)

**Comment by lamerise** [comment]
Implementatie vind ik nog niet helemaal optimaal.

Ik zou niet een vinkboxje zetten voor het type, maar alleen voor de waarden die je binnen het type kan aangeven..

Nu moet je eerst het type aanvinken en dan klapt ie open met daaronder al alle vinkjes van de opties aan.. Dat werkt niet intuitief want je wil 1 van die opties over het algemeen aanvinken.

Ik denk dat je de vinkjes kan weglaten voor de typen en ze altijd uit kan klappen.. Als dat te veel wordt zou je de typen uitklapbaar moeten maken

**Comment by copierrj** [comment]
Presentatie hoofdlijnen in inhoudsopgave is verbeterd: hoofdlijnen worden nu gegroepeerd op 'type'.
