### ISSUE TITLE
Bij filteren op gebiedsaanwijzing of activiteit of locatie in het kaartbeeld alleen de gebiedsaanwijzing, activiteit of locatie aanzetten waarop is gefilterd.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#112]
In alle andere gevallen alle gebiedsaanwijzingen van de geselecteerde teksten in het kaartbeeld aanzetten.

**Comment by HermanAssink** [comment]
Bij zoeken op gebiedsaanwijzing  "Bufferzone stiltegebied" in verordening van Utrecht worden ook andere gebiedsaanwijzingen aangezet:
![image](https://user-images.githubusercontent.com/2979044/218044054-3a105228-a280-4859-b1f6-474e702428d1.png)

**Comment by copierrj** [comment]
Enkel de annotaties achter de geselecteerde kenmerken worden nu op de kaart gezet.

**Comment by HermanAssink** [comment]
werkt naar tevredenheid
