### ISSUE TITLE
Naam van hoofdniveau in inhoudsopgave wijzigen van "regeling" in de naam van het type instrument, bijv. omgevingsverordening

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#113]

**Comment by MaxIDgis** [comment]
Dit pakken we op wanneer we bezig gaan met relaties tussen regelingversies en besluiten.

**Comment by HermanAssink** [comment]
Afgesproken is:

- bij artikelgewijze structuur -> regels
- bij vrije tekststructuur -> beleid
- bij besluit -> besluit
- bij kennisgeving -> kennisgeving

**Comment by copierrj** [comment]
@HermanAssink @MaxIDgis  Kan dit issue niet gesloten worden?

**Comment by HermanAssink** [comment]
Inderdaad, kan gesloten
