### ISSUE TITLE
Balk met foutmelding over PDOK/Locatieserver is niet weg te klikken

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#115]
Kruisje toevoegen en/of melding misschien automatisch na enkele seconden weghalen

**Comment by lamerise** [comment]
hoe testen we dit?

**Comment by HermanAssink** [comment]
Reijer heeft het in de ontwikkelomgeving getest door de fout op te roepen en daarbij geconstateerd dat het probleem is verholpen. Issue kan daarom m.i. gesloten worden.
