### ISSUE TITLE
Zoeken op tekst aanvullen met "ctrl-F" functie

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#116]
Voorbeeld:
Bij zoeken op natuur in verordening ZH wordt wel "natuurlijke" gevonden, maar natuurbescherming en natuurgebieden niet. Kan de zoekfunctie worden uitgebreid zodat ook woorden die beginnen met de zoektekst worden gevonden?

![image](https://user-images.githubusercontent.com/2979044/218044730-ff7a3e47-96f8-41b9-99bc-bbeffe350e29.png)

**Comment by HermanAssink** [comment]
Er worden nu suggesties getoond. Is deze oplossing afdoende?

**Comment by lamerise** [comment]
Nee, nog steeds komen niet alle dingen waar de letters natuur te voorschijn..

De natuurgebieden nog steeds niet.

Hij highlight ook het hele woord natuurlijke terwijl ik op "natuur" zocht" Dan zou ik alleen maar de letters "natuur gehighlight willen zien.

**Comment by lamerise** [comment]
Er komt nu wel meer en de goede dingen naar voren.

in de presentatie in de tekst zou het nog mooi zijn als alleen het precies gezochte woord de highlight krijgt. (en niet het hele woord waar een stukje van het gezochte woord in zit...

Bijv. wordt nu bij zoeken op natuur het hele woord natuurbescherming gehighlight

**Comment by HermanAssink** [comment]
De wensen mbt zoeken op woorden in de  tekst zit in #21
