### ISSUE TITLE
Legenda toevoegen

### ISSUE THREAD

**Issue by copierrj** [IDgis/PlanoView2-bevindingen#120]
Een legenda toevoegen aan het de kaart waarmee het mogelijk is de laagvolgorde te veranderen.

**Comment by copierrj** [comment]
Het veranderen van de de laagvolgorde werkt op dit moment enkel met muisbediening. Op een tablet is dit op dit moment dus nog niet mogelijk.

**Comment by HermanAssink** [comment]
werkt naar tevredenheid
