### ISSUE TITLE
Lange toelichtingtekst inklappen

### ISSUE THREAD

**Issue by copierrj** [IDgis/PlanoView2-bevindingen#121]

**Comment by CoraPU** [comment]
in los venster mist soms knopje toon meer 
![image](https://user-images.githubusercontent.com/30464824/219587717-c0fda30f-212b-4375-93d2-f711720510a3.png)

**Comment by lamerise** [comment]
knopje toon meer/ toon minder naar rechts verplaatsen ... en even goed kijken hoe je  de afdekking doet.. soms zie je dan drie puntjes aan het einde van een zin die je afbreekt.. Of iets met vervaging oid... 

knopje zelf zou wel iets meer kunnen opvallen

En ik vraag me af of je een halve zin moet laten zien... Kan je bewust wel of bewust niet doen...

**Comment by TitiaBaeten** [comment]
na weer inklappen van de toelichting springt de tekst niet terug naar de beginpositie van het artikel en toelichting
