### ISSUE TITLE
Icons toegevoegd aan links in de tekst

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#124]
i-teken bij begrippen en pijltjes bij interne en externe verwijzingen.

**Comment by lamerise** [comment]
Niet doen bij interne links.. Vind ik.. Maar hoor graag hoe anderen hier over denken

Het pijltje uit het vierkant is als notificatie bedoeld dat je deze pagina/site gaat verlaten

**Comment by HermanAssink** [comment]
Klik op link naar begrip werkt niet in Chrome, wel in Firefox

**Comment by HermanAssink** [comment]
Werkt ook niet in Edge

**Comment by HermanAssink** [comment]
Het pijltje bij interne verwijzingen moet nog worden weggehaald

**Comment by AnkeVanBeek-IDgis** [comment]
icoon interne verwijzing is niet meer zichtbaar
