### ISSUE TITLE
Viewer crasht bij klik op link naar GIO in tekstvenster bij Omgevingsverordening Brabant

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#128]
Reproduceren:
- https://test.viewer.planoview2-demo.idgis.eu/
- Open Omgevingsverordening Noord-Brabant
- Zet hoofdstuk 5 aan
- Klik op GIO Stedelijke gebied
![image](https://user-images.githubusercontent.com/2979044/225058761-1dc2ac1c-ef01-4edd-bea0-c8c93f7d15d7.png)

**Comment by copierrj** [comment]
Oorzaak van de crash: document bevat verwijzingen naar onbekende (lees: niet ingelezen) GIOs.

**Comment by copierrj** [comment]
De crash gemelde is verholpen. Bij nader inzien bevat het document toch geen verwijzingen naar onbekende GIOs maar bevat het verwijzingen naar pdf IOs. Deze verwijzing zal in een latere versie als hyperlink beschikbaar komen.

**Comment by HermanAssink** [comment]
Crash is verholpen
