### ISSUE TITLE
Opmaak/werking van de pop up "Zoek op kenmerken" kan nog wel wat beter/mooier

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#131]
Daarnaast is de opmaak en uitlijning nog niet zo fraai.

Bepaalde waarden uit waardelijsten zouden ook mooier uitgeschreven kunnen worden

Bijvoorbeeld juridischeregel > Type regel

Instructieregel
Regel voor iedereen
Omgevingswaarde (regel)  of Regel met/over een omgevingswaarde

Het "zoek in lijst" balkje is ook niet zo heel fraai vind ik...

**Comment by lamerise** [comment]
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/114915209/0287a13a-3ba1-4ec0-90ae-472511bc7f4a)


Wat meer ruimte tussen de buttons en meer ruimte tussen de teksten en de randen van de buttons (ongeveer evenveel ruimte als onder en boven de tekst)

Worden die in de domeinlijst aanElkaarGeschreven zijn uit elkaar halen...

**Comment by HermanAssink** [comment]
Nu wordt de mensleesbare variant van de labels getoond.

**Comment by CoraPU** [comment]
Ziet er beter uit zo. Alleen in zoek in lijst balkje de tekst mooier uitlijnen

**Comment by copierrj** [comment]
> Ziet er beter uit zo. Alleen in zoek in lijst balkje de tekst mooier uitlijnen

Is aangepast.
