### ISSUE TITLE
hoofdlijn waarde toont in legenda

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#132]
NA het zoeken en daarna selecteren van een hoofdlijn (selecteer resultaat) verschijnt de hoofdlijn waarde in het legenda boxje..

Is dat bewust en is dat de bedoeling?

**Comment by copierrj** [comment]
Is niet te bedoeling. Zal het verhelpen.

**Comment by copierrj** [comment]
In de vorige versie probeerde de viewer ten onrechte typen annotaties zonder geometrie (zoals hoofdlijnen) op de kaart te zetten. Bij selectie van dergelijke annotaties met behulp van het kenmerken zoekscherm worden nu de gebiedsaanwijzingen bij gevonden artikelen geactiveerd.
