### ISSUE TITLE
PDF's die informatieobjecten zijn (in dus in bijlage I zijn opgenomen) in viewer  kunnen openen, zie Omgevingsverordening Brabant

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#135]

**Comment by lamerise** [comment]
Hoe open je dan de pdf?

Graag een "link" knopje achter het informatieobject in bijlage II 

(net als het knopje achter een gio in bijlage II)

**Comment by copierrj** [comment]
Download link staat op twee plaatsen,

In de bijlage met informatieobjecten:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2194475/1e8c7297-9783-4a53-a08c-13589cbeb2db)

Elders in het document bij de verwijzing naar het informatieobject:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2194475/99b72e89-bfb8-435a-939f-cb7d9ef1e74f)

**Comment by HermanAssink** [comment]
Nadat documenten opnieuw geladen zijn wordt het 
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/65c1cc05-04da-4e87-b82b-7eac60711a76)
icon zichtbaar bij betreffende pdf
