### ISSUE TITLE
Hoe activiteitlocatieaanduiding met bijbehorende regelkwalificatie weergeven in legenda?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#137]
Omdat een bepaalde activiteit bij ieder artikel/lid een andere locatie en regelkwalificatie kan horen, zie een herhaling van legenda-eenheden.

**Comment by HermanAssink** [comment]
Complex voorbeeld: 
![image](https://user-images.githubusercontent.com/2979044/227468973-f6f840fd-6bfa-4fba-8af7-8964a99a6e5f.png)

**Comment by HermanAssink** [comment]
Wens is om locatienaam toe te voegen in de legenda in de volgorde: activiteitnaam (regelkwalificatie) locatienaam. 
En legenda-eenheden uniek te maken op basis van deze drie kenmerken en het symbool. (Het symbool kan eventueel variëren als het specifiek voor betreffende activiteitlocatieaanduiding is toegekend)

**Comment by copierrj** [comment]
Een activiteitlocatieaanduiding kan meerdere locaties bevatten. Dit zou dus meerdere locatienamen per legenda item betekenen.

**Comment by HermanAssink** [comment]
Inderdaad, maar dit zal niet vaak voorkomen. Het is natuurlijk wel extra ontwikkelwerk.

**Comment by copierrj** [comment]
Komt vaker voor dan je zou denken.

**Comment by copierrj** [comment]
Na overleg: samenvoegen tot 1 legenda item per activiteit.

**Comment by HermanAssink** [comment]
Is opgelost met de verbetering zoals beschreven in #155
