### ISSUE TITLE
Bij artikelgewijze toelichting de toelichting weergeven bij het artikel/lid zoals in PlanoView1

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#14]
- toelichting koppelen aan regel. zodat de toelichting getoond wordt bij de regel

**Comment by HermanAssink** [comment]
Implementeren gebruik makend van expliciete verwijzing tussen toelichting en betreffend artikel (is aangepast in de STOP-standaard). Oppakken zodra er content is.

**Comment by CoraPU** [comment]
bij zoeken wordt tekst  niet gevonden in toelichting in blok  bij artikel maar alleen in de artikelgewijze toelichting onderaan in regeling

**Comment by copierrj** [comment]
Bij zoekresultaat in toelichting bij een artikel wordt het artikel zelf nu ook in het zoekresultaten opgenomen.

**Comment by HermanAssink** [comment]
werkt nu
