### ISSUE TITLE
iPad: in vertikale opmaak (Limburg) is openen legenda niet mogelijk

### ISSUE THREAD

**Issue by AnkeVanBeek-IDgis** [IDgis/PlanoView2-bevindingen#140]
Bij openklappen van de legenda wordt het scherm waarschijnlijk op dezelfde plaats geprojecteerd als het tekst-deel.  Daarna wordt het tekst-deel er bovenop geplaatst.
Indien het tekst-deel eerst ingeklapt is (of minimaal zichtbaar), dan wordt het legenda-scherm wel zichtbaar.

**Comment by HermanAssink** [comment]
Kun je een screenshot bijvoegen?

**Comment by AnkeVanBeek-IDgis** [comment]
![B5256E20-F6A0-4224-BECC-06BD5E5763B5](https://user-images.githubusercontent.com/106512936/231110646-74d06213-0426-4716-9262-14267578e92c.png)
![4543C53D-74F8-49D1-8509-E27B4CCE041E](https://user-images.githubusercontent.com/106512936/231110653-5ee7e4c2-e1b0-428f-8ed3-52c7ccd4f7f8.png)

**Comment by copierrj** [comment]
Nu de legenda over het kaartbeeld heen ligt is dit niet langer een issue.
