### ISSUE TITLE
Werken met groepsindeling voor plannen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#144]
Er kunnen groepen met plannen worden gemaakt en gewijzigd. De viewer opent de default groep. Ook kunnen andere groepen geselecteerd worden.

**Comment by lamerise** [comment]
Het lijkt er op dat als ik plannen van andere overheden (andere cbs code) toevoeg deze niet tonen in een groep. Bijvoorbeeld, omgevingsplannen worden in de viewer in de groep omgevingsplannen niet getoond.

**Comment by HermanAssink** [comment]
Bij klik op de knop Viewer wordt bij alle provincies de viewer van Utrecht geopend. Dit moet de viewer van de ingelogde beheerder zijn.

**Comment by MaxIDgis** [comment]
De viewer knop is voor nu weg gehaald. Er is een nieuwe pagina met sites bijgekomen, daar heeft elke site een klikbaar domein om bij die site te komen. Als een site de gewenste groep bevat, is de groep via daar te bekijken.

Sites zijn een nieuw concept beschreven in [Planoview2-bevindingen#144](https://github.com/IDgis/PlanoView2-bevindingen/issues/147)

**Comment by MaxIDgis** [comment]
> Het lijkt er op dat als ik plannen van andere overheden (andere cbs code) toevoeg deze niet tonen in een groep. Bijvoorbeeld, omgevingsplannen worden in de viewer in de groep omgevingsplannen niet getoond.

Ik kan op de testomgeving wel plannen van andere overheden zien, volgens mij is dit ondertussen opgelost.

**Comment by lamerise** [comment]
Ik kan de groep zelf niet als subgroep toevoegen... dat kon in planoview 1 wel.. Dat was wel handig om een rustiger interface te krijgen bij het gebruik van groepen

**Comment by lamerise** [comment]
in mijn site "omgevingsdocumenten" klopt de volgorde in de voorkant niet met mijn instelleningen aan de achterkant in de admin

**Comment by lamerise** [comment]
graag zou ik zien dat de viewer met "/groepsnaam" in de url zou gaan werken.

Dan kan ik daar direct naar linken en ook beter controleren of mijn groepsinstellingen nu goed gaan.

**Comment by HermanAssink** [comment]
Aanvulling: Als voor de groepsnaam een moeilijk te raden naam wordt gekozen en deze als "/groepsnaam" gebruikt kan worden dan is dit te gebruiken als beveiliging. Voordeel van het gebruik van een moeilijk te raden groep met vertrouwelijke plannen is dat de inhoud van de groep kan wijzigen zonder dat een andere url gebruikt moet worden. Beveiliging obv van ingelogde gebruiker wordt dan niet nodig gevonden.

**Comment by MaxIDgis** [comment]
> Ik kan de groep zelf niet als subgroep toevoegen... dat kon in planoview 1 wel.. Dat was wel handig om een rustiger interface te krijgen bij het gebruik van groepen

Dat klopt, dat heb ik voor nu inderdaad niet toegestaan. Op wat voor een manier maakt het de interface rustiger als je de groep bij zichzelf als subgroep toevoegt?

**Comment by MaxIDgis** [comment]
> in mijn site "omgevingsdocumenten" klopt de volgorde in de voorkant niet met mijn instelleningen aan de achterkant in de admin

Zou je een plaatje van de voorkant en achterkant toe willen voegen? Dan kan ik zien of ik hetzelfde kan reproduceren

**Comment by lamerise** [comment]
startsite van omgevingsdocumenten.zuid-holland.nl
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/114915209/fc53fa36-771f-4ae0-8da9-a4e678fdcf13)

terwijl dit in de sites staat:

![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/114915209/4285bf4a-5267-4c40-8567-105be9b5f3b7)


De "Home" groep staat in de site onderaan.. Maar in de admin bovenaan...

De andere groepen staan ook niet in de goede volgorde zie ik nu... Lijkt alleen bij sites niet goed te gaan.. Bij groepen wel als je daar een volgorde set.

**Comment by lamerise** [comment]
> > Ik kan de groep zelf niet als subgroep toevoegen... dat kon in planoview 1 wel.. Dat was wel handig om een rustiger interface te krijgen bij het gebruik van groepen
> 
> Dat klopt, dat heb ik voor nu inderdaad niet toegestaan. Op wat voor een manier maakt het de interface rustiger als je de groep bij zichzelf als subgroep toevoegt?

In onze huidige planoview heb je dan het groepenlijstje altijd even lang.. Dan geeft bij navigeren door de groepen een rustiger beeld.. Anders mist steeds de groep waar je in zit op dat moment en verspringt steeds alles.

Zie ruimtelijkeplannen.zuid-holland.nl

**Comment by MaxIDgis** [comment]
> De "Home" groep staat in de site onderaan.. Maar in de admin bovenaan...
> 
> De andere groepen staan ook niet in de goede volgorde zie ik nu... Lijkt alleen bij sites niet goed te gaan.. Bij groepen wel als je daar een volgorde set.

Dankjewel voor het plaatje, de fix is onderweg

**Comment by MaxIDgis** [comment]
> > > Ik kan de groep zelf niet als subgroep toevoegen... dat kon in planoview 1 wel.. Dat was wel handig om een rustiger interface te krijgen bij het gebruik van groepen
> > 
> > 
> > Dat klopt, dat heb ik voor nu inderdaad niet toegestaan. Op wat voor een manier maakt het de interface rustiger als je de groep bij zichzelf als subgroep toevoegt?
> 
> In onze huidige planoview heb je dan het groepenlijstje altijd even lang.. Dan geeft bij navigeren door de groepen een rustiger beeld.. Anders mist steeds de groep waar je in zit op dat moment en verspringt steeds alles.
> 
> Zie ruimtelijkeplannen.zuid-holland.nl

Dat is inderdaad op die manier makkelijk te bereiken. Ik heb het toevoegen van een groep bij zichzelf als subgroep toegestaan.
