### ISSUE TITLE
Filterfunctie inhoudsopgave bedienen dmv knopje naast de drie knopjes inklappen, uitklappen en selectie opheffen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#145]
Knop die nu wordt gebruikt neemt teveel ruimte. 
Filter-icon gebruiken als knopje met indicatie of het filter al of niet actief is.

**Comment by Brtvrlndn** [comment]
filterfunctie werkt na 1 keer gebruik niet meer

**Comment by HermanAssink** [comment]
@Brtvrlndn Hoe kunnen we dit probleem reproduceren? Het lijkt mij om het te reproduceren.

**Comment by MaxIDgis** [comment]
De tooltip van de filterknop is aangepast om misverstanden te voorkomen.
