### ISSUE TITLE
Site functionaliteit

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#147]
In de admin is nieuwe functionaliteit bijgekomen onder een nieuwe pagina Sites:
![Screenshot_sites](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/1a6d65f7-4e58-46c2-82e7-28190712bfce)

Deze sites stellen jullie in staat om de omgeving van de viewer in te richten. Voor nu kunnen jullie alleen nog groepen aan een site toewijzen, maar uiteindelijk zullen hier ook extra configuratie opties landen.
Zoals in het plaatje te zien is, heb ik twee sites, een site "Test" en een site "Rijssen-Holten".

Sites kunnen meerdere domeinnamen hebben, om zo een alias in te kunnen stellen.

Hoe een site zich in de viewer gedraagt ligt aan de hoeveelheid groepen die zijn toegewezen aan de site.
Als een site zonder groepen bezocht wordt, heeft deze site geen documenten om te laten zien en krijg je in de viewer een melding dat de site ingericht moet worden.
Als een site met één groep bezocht wordt, krijgt een bezoeker van de viewer gelijk de inhoud van die groep te zien.
Als een site twee of meer groepen heeft, moet een bezoeker eerst uit een van die groepen kiezen voordat de bezoeker documenten of subgroepen te zien krijgt.

Op de testomgeving mist op dit moment de kolom met site namen, maar die vond ik zo essentieel voor de duidelijkheid van de uitleg dat ik de screenshot met naamkolom heb gemaakt.

**Comment by lamerise** [comment]
Graag ook een uitleg hoe het werken met groepen werkt... Ik zal hier niet zo veel instellen verwacht ik.. omdat er eerst door de julliein overleg met onze ict een site aangemaakt en ingeregeld moet worden.

Wat je hier nu vooral zelf moet instellen is hoe je site start.. Met welke groep of groepen.. In planoview 1 was dat een "default" groep in de groepenlijst die je niet van naam kon veranderen... klopt dat?

Nu is dat er niet meer onder groepen...

**Comment by HermanAssink** [comment]
> Graag ook een uitleg hoe het werken met groepen werkt... Ik zal hier niet zo veel instellen verwacht ik.. omdat er eerst door de julliein overleg met onze ict een site aangemaakt en ingeregeld moet worden.
> 
> Wat je hier nu vooral zelf moet instellen is hoe je site start.. Met welke groep of groepen.. In planoview 1 was dat een "default" groep in de groepenlijst die je niet van naam kon veranderen... klopt dat?
> 
> Nu is dat er niet meer onder groepen...

Het "default groep" principe is nu te realiseren door aan een site één groep te koppelen. Deze groep wordt dan automatisch getoond. In die ene groep kunnen weer andere groepen (en plannen) zitten.

**Comment by MaxIDgis** [comment]
Je kan inderdaad dezelfde "default groep" functionaliteit bereiken door maar 1 groep aan de site toe te wijzen.
Als je bij binnenkomst gelijk een lijst van documenten (met of zonder subgroepen) wil laten zien, dan is dit de manier om dat te doen.

Als je bij binnenkomst op de site alleen een lijst groepen wil tonen waarbij je eerst een groep moet selecteren voordat je een document kan selecteren (volgens mij is dat de situatie op https://zuidholland.planoview.nl/), dan kan dat nu op twee manieren.
Je kan nog steeds gebruik maken van de "default groep" door 1 groep toe te wijzen aan de site en de andere groepen als subgroepen toewijzen aan deze "default groep".
De tweede optie is om die lijst groepen direct aan de site toe te wijzen.
Dit zou er in de viewer hetzelfde uit moeten zien, dus dat is maar net wat jullie handiger lijkt aan de kant van de admin.

**Comment by HermanAssink** [comment]
Het werken met groepen is nu volledig ontwikkeld.
