### ISSUE TITLE
Verbeteringen UserInterface

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#148]
De UI verbeteringen zijn "werk-in-uitvoering". Hieronder is vermeld wat inmiddels is gedaan en wat nog moet gebeuren.

Gedaan:

    Algemeen
        rustigere UI
        minder op het scherm
        geen lijntjes
        meer padding
        minder brede balken tussen tekst, kaart en inhoudsopgave
    Kenmerken
        Layout knoppen verbeterd
        Knoppen tbv type selectie (was: radio buttons)
        Zoeken in lijst met highlight gevonden match
    Inhoudsopgave
        selecteren dmv klikken op oogje of op titel
        deselecteren dmv oogje
        icoonjes enkel zichtbaar bij hover (vraag: is het een probleem dat het niet langer mogelijk is om precies te zien welke artikelen annotaties en/of locaties hebben?
    Kaartviewer
        knoppen zonder tekst waarbij met een klik (idee: hover?) een menu opent (om ruimte te besparen)
        ondergrondkaartselectie met preview
        legenda over de kaart ipv naast de kaart

Todo:

    Overwegen / proberen de titelbalk overbodig te maken
    Kenmerken scherm:
        knoppen altijd zichtbaar
    rustigere layout (meer padding)

Experimenteren met zachtere kleuren
Idee: kleur knoppen in sommige gevallen inverteren (blauwe knoppen met witte tekst in geval van IDgis huisstijl)
Consistentie in knoppen + menu kaartviewer

    wel/geen titels
    wel/geen border
    wel/niet sluiten bij klik elders

Idee: oogje achter symbool zodat marge links kleiner kan
Verbeterpunt: vingervriendelijkheid (tablet) balken tussen tekst, kaart en inhoudsopgave, oplossingsrichting: 'beetpak element' toevoegen

**Comment by lamerise** [comment]
Selecteer kaart zou ik iets anders mee willen.

Niet zo prominent onder de simpele zoek functie

**Comment by lamerise** [comment]
Ik zou nog proberen wat lijnen weg te halen.

In de ontwerpen is er eigenlijk maar 1 (zeer zachte) functionele lijn te zien.. En dat is een verticale tussen de inhoudsopgave/controls links en het kaart en tekst vak rechts.. (de scheiding tussen het kaart en tekstvak ontstaat eigenlijk vanzelf door de topo/lufo achtergrond van de kaart)

En afhankelijk hoe je een kop/header gebruikt zit daar evt ook nog een horizontale lijn...

Ik denk dat je daardoor een rustigere uitstraling krijgt

Onze planoview 1 heeft een wat softere uitstraling doordat de lijnen zeer licht zijn.. Dat helpt ook al.

**Comment by lamerise** [comment]
tekst achter legenda kleur blokje kan nog wat kleiner (is nu groter dan al de andere tekst)

**Comment by lamerise** [comment]
preview van het instellen van de achtergrond op 1 schaalniveau houden, of iig niet te ver inzoomen.. (dan zie je soms niets meer)

Alternatief is het altijd een paar schaalniveau's boven het zichtbare kaartbeeld te houden zodat je in het kleine vakje ongeveer hetzelfde ziet (dezelfde extent) als in het grote kaartvenster.. Dat is denk ik ook al logischer voor de gebruiker.

Idee om dynamisch het centrum van de huidige zichtbare kaart te volgen is wel goed.

**Comment by HermanAssink** [comment]
Dat de icons aan de rechterkant in de inhoudsopgave alleen bij hoover over een item verschijnen wordt akkoord bevonden. Als tussenoplossing wordt het tonen van icons bij geslecteerde items genoemd, maar deze tussenoplossing heeft uiteindelijk niet de voorkeur.

**Comment by copierrj** [comment]
De lijnen tussen de verschillende onderdelen (kaart, tekst en inhoudsopgave) zijn dunner geworden en voor het vergroten/verkleinen van onderdelen is nu een aparte 'grip' control toegevoegd in aanvulling op de de reeds bestaande knopen om onderdelen volledig te verbergen.

**Comment by CoraPU** [comment]
locatie Knop open plan naast logo PU vind ik niet mooi  ook de andere knoppen in de rode balk nu een beetje grof.  Boven de zoekbalk was wat subtieler maar nu wel meer ruimte voor de inhoudsopgave.  

knop geavanceerd zoeken uitlijning niet goed met zoekbalk
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/30464824/8a5d888b-39a6-47ed-9a33-e5277a939c4d)

**Comment by lamerise** [comment]
ik zou de knoppen in de header ook liever klein/normaal zien
Ik zou ook geen "raket" doen als symbooltje voor geavanceerde instellingen.

Misschien een vergrootglasje met tandwieltje.. Daar zijn wel aardige voorbeeldjes van de vinden op internet (en waarschijnlijk ook wel in jullie icoon bibliotheer

**Comment by Brtvrlndn** [comment]
kunnen de knoppen "boek open" en "boek dicht" worden gecombineerd en functioneren als een soort radio-button?

**Comment by Brtvrlndn** [comment]
we missen toch nog een button om alle selecties (tekst/kaart en andere filtering) te neutraliseren en opnieuw te beginnen binnen het gekozen Omgevingsdocument

**Comment by Brtvrlndn** [comment]
kleine frustratie: kan de afstand tussen tekst en kaart iets groter in de Limburg modus (erg druk)

![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/115712307/9bd51fc5-7765-43c2-b3ad-5077a8d4eeb9)

**Comment by Brtvrlndn** [comment]
zoekvenster linksboven heeft geen functie meer bij geavanceerd zoeken (en werkt dus ook verwarrend). 

suggestie: bij geavanceerd zoeken dit gewone zoekvenster volledig vervangen door het geavanceerde zoekvenster; dit is minder verwarrend en minder druk:

![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/115712307/82111872-1d42-4158-913e-fb8ea83eef20)

**Comment by lamerise** [comment]
Ik vind de woorden "site" en "groep" niet zo fraai in de menu's van de groepen etc.. Kan dat ook weg?

**Comment by lamerise** [comment]
de titel van de site is nog planoview.. Zou ook de sitenaam mogen zijn...

**Comment by copierrj** [comment]
> zoekvenster linksboven heeft geen functie meer bij geavanceerd zoeken (en werkt dus ook verwarrend).
> 
> suggestie: bij geavanceerd zoeken dit gewone zoekvenster volledig vervangen door het geavanceerde zoekvenster; dit is minder verwarrend en minder druk:
> 
> ![image](https://user-images.githubusercontent.com/115712307/246841715-82111872-1d42-4158-913e-fb8ea83eef20.png)

Dit issue is verholpen door een iets grotere marge toe te passen.

**Comment by copierrj** [comment]
> kleine frustratie: kan de afstand tussen tekst en kaart iets groter in de Limburg modus (erg druk)
> 
> ![image](https://user-images.githubusercontent.com/115712307/246837839-9bd51fc5-7765-43c2-b3ad-5077a8d4eeb9.png)

Dit issue is verholpen door een iets grotere marge toe te passen.
