### ISSUE TITLE
Delen van viewer toestand 

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#149]
De knop "Deel met anderen" werkt nu. Op de manier is de toestand van de viewer, zoals geselecteerde documenten en teksten, kaartextent, e.d. te delen.

**Comment by lamerise** [comment]
Lijkt goed te werken...

Zou ook van /groepsnaam naar een groep willen kunnen gaan (is stabieler dan de toestand delen)

En misschien zelfs ook naar /akn naar een plan/versie oid..  (was in planoview 1 het IMRO nummer).

/groepsnaam/IMRO-nummer werkte ook in planoview 1 en gebruiken we ook regelmatig. (kom je namelijk ook meteen in de goede groepscontext (als er bijvoorbeeld meer samenhangende plannen tegelijk in een groep ter inzage liggen)

**Comment by HermanAssink** [comment]
Bovenstaande opmerkingen hebben betrekking op #147

**Comment by HermanAssink** [comment]
Op de functie delen van de viewertoestand zijn geen bevindingen
