### ISSUE TITLE
labels hoofdstuk/afdeling/paragraaf etc

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#15]
De inhoudsopgave in de huidige viewer is rustiger qua beeld. Hier worden niet de labels hoofdstuk/afdeling/paragraaf/subparagraaf getoond in de inhoudsopgave/tekst. Dit wordt alleen getoond bij het artikel en lid.

Dit ook in de nieuwe viewer alleen bij artikel en lid. Bij het lid wordt nu alleen de nummers getoond hier wel lid 1 lid 2 etc zowel in inhoudsopgave als de tekst.

**Comment by HermanAssink** [comment]
@CoraPU Voorbeeld: In het STOP-bestand van de omgevingsverordening staat:
`<Kop>
	<Label>Hoofdstuk</Label>
	<Nummer>2</Nummer>
	<Opschrift>Watersysteem</Opschrift>
</Kop>
`

Volgens de STOP-standaard is tenminste één van de drie (Label, Nummer en Opschrift) verplicht. In het algemeen is voor regelingen van alle bevoegde gezagen dus niet wenselijk om het element Label altijd weg te laten. Moet je kunnen configureren welke van de drie elementen weergegeven moeten worden?
