### ISSUE TITLE
Titelbalk laten vervallen, logo zwevend boven het kaartbeeld

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#151]
Is het een idee om, als we de titelbalk laten vervallen, het logo zwevend boven het kaartbeeld te plaatsen om op die manier maximaal hoogte te winnen voor de inhoudsopgave?

**Comment by MaxIDgis** [comment]
We gaan de functieknoppen boven zoeken in de header zetten. Zie [151](https://github.com/IDgis/PlanoView2-bevindingen/issues/154)
