### ISSUE TITLE
eerste zoomstap viewer limburg

### ISSUE THREAD

**Issue by TitiaBaeten** [IDgis/PlanoView2-bevindingen#152]
Bij opstarten van de verordening in de viewer Limburg is Limburg eerst relatief klein en na de eerste zoomstap verdwijnen het noordelijk en zuidelijk deel buiten beeld. Zou de eerste zoomstap kleiner kunnen?
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/119037891/fdb7d590-9eb6-4772-857f-0aed6fda464e)
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/119037891/3b5f4e13-2957-43cf-aa3f-cab187f90c5c)

**Comment by copierrj** [comment]
We zijn gebonden aan de schaalgrenzen van de Nederlandse richtlijn tiling. Dit omdat de BRT-achtergrondkaart enkel op deze schalen beschikbaar is. Hoewel het technisch gezien mogelijk is om tussen twee schaalgrenzen in te gaan zitten levert dit een wazige achtergrondkaart op.
