### ISSUE TITLE
bij opgengeklapte zoekfuncties wordt de ruimte voor inhoudsopgave te klein

### ISSUE THREAD

**Issue by TitiaBaeten** [IDgis/PlanoView2-bevindingen#154]
bij opengeklapte zoekfuncties wordt de ruimte voor inhoudsopgave te klein. 

![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/119037891/a7cbb63e-93df-4cf3-877e-0a5c448cf3a7)

**Comment by HermanAssink** [comment]
Knoppen Selecteer en Verwijder zijn verkleind en naast elkaar gezet. Knop om resultaten te filteren is een icon geworden. Suggestie: Er is nog meer ruimte te winnen door de titel balk te laten vervallen en het logo zwevend boven het kaartbeeld te zetten.

**Comment by Brtvrlndn** [comment]
suggestie: knoppen "klap alles open" en "klap alles dicht" kunnen samen (toggle). weer een knop minder:)

**Comment by lamerise** [comment]
suggestie om de afdrukken etc functies eens in de header te zetten (rechts)

En het openen "links" naast het logo uitlijnen.

**Comment by lamerise** [comment]
er is nu ook twee keer een home knopje (ook in de kaart)... 
zou ook kunnen door een klik op het logo mogelijk te maken (algehele reset)

**Comment by HermanAssink** [comment]
Twee aanpassingen:

1. De "overall" Home knop is vervallen. Hiervoor in de plaats gaat de viewer bij een klik op het logo naar de begintoestand van de viewer
2. De algemene icons zijn verplaatst naar de titelbalk waardoor de regel met deze icons in het bedieningsvenster is vervallen.
