### ISSUE TITLE
selectie kenmerken activiteiten

### ISSUE THREAD

**Issue by TitiaBaeten** [IDgis/PlanoView2-bevindingen#155]
Bij selectie op activiteiten worden per annotatie van de activiteit in de tekst een kaartlaag getoond
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/119037891/a0926e88-8276-4510-b2be-ccdac3ef1bdf)

**Comment by HermanAssink** [comment]
Voor de legenda worden activiteiten nu gebundeld op activiteit en niet meer uitgesplitst naar regeltekst, locatie en regelkwalificatie

**Comment by Brtvrlndn** [comment]
werkt goed
