### ISSUE TITLE
bij klik op de kaart worden te veel resultaten getoond

### ISSUE THREAD

**Issue by TitiaBaeten** [IDgis/PlanoView2-bevindingen#156]
bij klik op de kaart, in onderstaand voorbeeld binnenstad Weert, worden veel te veel resultaten getoond, ook die niet van toepassing zijn op het gebied. 
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/119037891/77a2cdf0-f646-4431-b6a4-87be452025e9)

**Comment by HermanAssink** [comment]
In de inhoudsopgave worden wel de goede teksten getoond, maar in het kaartbeeld wordt teveel getoond.

**Comment by HermanAssink** [comment]
Bijvoorbeeld: Als je in de bebouwde kom van Weert klikt dan wordt o.a. de laag Stiltegebied aangezet, terwijl alle regelteksten met gebiedsaanwijzing Stiltegebied ook het werkingsgebied Stiltegebied hebben,

**Comment by HermanAssink** [comment]
Bij het zoeken op locatie (dmv klik in de kaart of op adres) worden nu alleen de gebiedsaanwijzingen aangezet die overlappen met de gezochte locatie

**Comment by lamerise** [comment]
> Bij het zoeken op locatie (dmv klik in de kaart of op adres) worden nu alleen de gebiedsaanwijzingen aangezet die overlappen met de gezochte locatie

Ik had de uitleg hierover deze ochtend niet helemaal meegekregen/begrepen, maar dit is/was toch altijd al de standaardafspraak om de vele gebieden te voorkomen. Alleen bij specifiek zoeken op activiteiten komen die gebieden...

OF zouden we met een klik op de kaart juist wel alle werkingsgebieden tonen (is ook wat voor te zetten)...

Echter als dat het ambtsgebied of de provinciegrens is zou je dat niet moeten willen lijkt mij

**Comment by lamerise** [comment]
Er is dus nu wel een verschil tussen selecteren en tonen..

Want het lijkt nog wel dat alle teksten met werkingsgebieden worden geselecteerd.. Dat is iig wel heel belangrijk.

**Comment by lamerise** [comment]
Wat niet zo duidelijk is aan de selectie in de inhoudsopgave is dat alleen tekstelementen met inhoud worden gehighlight (geel).. Bijv lid 1 en 2 van een artikel.. Maar het artikel zelf niet.

Ik denk dat als alle onderliggende elementen met inhoud zijn geselecteerd je ook de bovenliggende elementen moet selecteren.

Voor deelselecties zou je ook nog een visuele oplossing kunnen bedenken.

**Comment by HermanAssink** [comment]
@TitiaBaeten Wil jij controleren of deze issue gesloten kan worden?

**Comment by TitiaBaeten** [comment]
Getest en alleen die gebiedsaanwijzigingen die van toepassing zijn op die locatie worden getoond. Dus dat werkt.

Als je vervolgens een andere locatie aanklikt en je selecteert de resultaten blijven de resultaten van de vorige locatie ook nog zichtbaar. Zou mooi zijn als deze verdwijnen, net zoals bij een nieuwe zoekopdracht in de zoekbalk

**Comment by HermanAssink** [comment]
> Getest en alleen die gebiedsaanwijzigingen die van toepassing zijn op die locatie worden getoond. Dus dat werkt.
> 
> Als je vervolgens een andere locatie aanklikt en je selecteert de resultaten blijven de resultaten van de vorige locatie ook nog zichtbaar. Zou mooi zijn als deze verdwijnen, net zoals bij een nieuwe zoekopdracht in de zoekbalk

In het algemeen werkt het zo dat bij klikken op Selecteer de tekstelementen worden aangezet die nog niet aanstaan, bij deze functie worden niet eerst alle tekstelementen uitgezet. Dat werkt op deze manier zowel bij een klik in de kaart als zoeken op adres. Ook bij zoeken op woorden in de tekst of kenmerken zorgt Selecteer ervoor dat tekstelementen worden aangezet die nog niet aanstaan.
