### ISSUE TITLE
Het printen van de geselecteerde tekst en bijbehorend kaartbeeld

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#157]
Deze functionaliteit kan worden getest

**Comment by HermanAssink** [comment]
Bevindingen:

1. "(todo)" kan weg bij de knop
2. Rechthoekjes waarin legendasymbolen staan mogen kleiner, zowel in viewer als print
3. Als een legenda-item in de preview-viewer wordt uitgevinkt moet deze ook verdwijnen in de geprinte legenda.
4. Mogelijkheid te kiezen of kaart en/of tekst geprint moet worden.
5. Tekst moet op een nieuwe pagina beginnen
6. Als legenda niet onder kaartbeeld op 1e pagina past dan in zijn geheel naar 2e pagina verplaatsen.
7. Als je kiest voor liggende pagina bij Limburg dan komt het onderste deel van het kaartbeeld op de 2e pagina.
8. Is het mogelijk om in de preview-viewer al te kiezen voor liggend of staand afdrukken?

**Comment by HermanAssink** [comment]
Punt 1 t/m 5 zijn opgelost

**Comment by lamerise** [comment]
Ik zou ipv print het woord afdrukken gebruiken.. (Dat is de microsoft standaard (in de NL taal), ik weet niet voor apple).

JE kan nu en de tekst en de kaart uitzetten en dan blijft er niets over.. Dat is niet handig. 

Ik zou ook niet te veel tekst bij de knoppen willen.. Eigenlijk zou de bediening/de symbools voor zichzelf moeten spreken..

**Comment by MaxIDgis** [comment]
> Ik zou ipv print het woord afdrukken gebruiken.. (Dat is de microsoft standaard (in de NL taal), ik weet niet voor apple).

Dit zal ik gelijk aanpassen.

> JE kan nu en de tekst en de kaart uitzetten en dan blijft er niets over.. Dat is niet handig.

Dat klopt, mij leek dat niet zo'n probleem aangezien de gebruiker dat naar mijn idee gelijk doorheeft en weer kan veranderen. In PlanoView 1 kan dit natuurlijk niet, daar wordt door middel van drie knoppen gekozen wat er geprint moet worden.

Met drie extra knoppen vond ik het PlanoView 2 venster wat druk worden, vandaar dat ik heb gekozen voor twee knoppen, met als resultaat dat een gebruiker alles uit kan zetten.

Ik kan dit natuurlijk alsnog maken zoals in PlanoView 1, maar dan moet er dus wel een extra knop bijkomen. Is dat inderdaad hoe we het willen?

> Ik zou ook niet te veel tekst bij de knoppen willen.. Eigenlijk zou de bediening/de symbools voor zichzelf moeten spreken..

Met de suggestie hierboven kunnen we denk ik de tekst bij de knoppen over kaart en tekst afdrukken wel weghalen. Bij de afdruk knop zie ik dat ook gelijk wel werken.

De knop voor het toevoegen en verwijderen van een beschrijving wordt misschien wat onduidelijker als ik daar de tekst van weghaal en verder niks doe. Dan kun je namelijk niet meer aan de knop zelf zien of de beschrijving is toegevoegd of niet.

Hier zie ik dan twee oplossingen voor, of ik geef de knop een soort "ingedrukte" look als je hem aanklikt (zou ik ook moeten doen voor de PlanoView1-stijl "kaart/tekst/kaart+tekst" knoppen) of ik [voeg een slider toe](https://www.w3schools.com/howto/howto_css_switch.asp)

Als we de kaart en tekst knoppen twee aparte knoppen laten zouden we hier eventueel ook sliders van kunnen maken.

Wat lijkt jou het handigst @lamerise?

**Comment by MaxIDgis** [comment]
Ik heb voor nu de volgende drie dingen gedaan:
1. De heading van het afdrukvenster is nu "Afdrukken" in plaats van "Print"
2. De twee knoppen voor het aan/uit zetten van de kaart of tekst zijn nu samengevoegd tot drie knoppen à la PlanoView 1
3. De hoeveelheid tekst bij de knoppen is verminderd

Ik ben benieuwd hoe dit bevalt

**Comment by Brtvrlndn** [comment]
ziet er al een stuk beter, echter:
- onduidelijk welke optie gekozen is (alleen kaart/ tekst of beiden). suggestie: gekozen optie grijs laten na aanklikken
- schaalbalk ontbreekt in printpreview (afstand wel)
- logo kan helft kleiner
- kaart is vierkant oké: dus zoveel mogelijk uitvullen tot rechtermarge bij staande print; legenda rechts van de kaart bij liggende print
- rand om titel weg

**Comment by MaxIDgis** [comment]
Ik heb weer wat veranderingen gemaakt
- De gekozen optie is nu grijs
- De schaalbalk is zichtbaar in de print
- Ik heb een maximum grootte ingesteld voor logos
- De rand om de beschrijving is weg bij het printen. In het keuzevenster is deze rand er nog wel om het makkelijker te maken om de grootte van het bescrhrijvingen veld aan te passen.

Ik heb alleen niks gedaan met liggende print. Zodra het print preview venster is geopend kan ik helaas niks meer doen met de pagina layout. Als je dus wisselt naar liggende layout, kan ik de legenda helaas niet naast de kaart plaatsen.

**Comment by HermanAssink** [comment]
Bovenstaande verbeteringen staan op de testomgeving.

**Comment by CoraPU** [comment]
- in de legenda wordt het kleurblokje niet volledig weergegeven. 
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/30464824/24e4dc12-298c-41f2-9ccf-61284a4c781a

- Als van staand naar liggend komt alleen logo op 1e pagina en kaart op 2e

**Comment by HermanAssink** [comment]
> * in de legenda wordt het kleurblokje niet volledig weergegeven.
>   ![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/30464824/24e4dc12-298c-41f2-9ccf-61284a4c781a
> * Als van staand naar liggend komt alleen logo op 1e pagina en kaart op 2e

Liggende weergave is niet eenvoudig goed werkend te realiseren. Daarom zou stel ik voor geen rekening te houden met deze mogelijkheid (werkt ook niet in PlanoView1).

**Comment by HermanAssink** [comment]
Extra wens: Kunnen kiezen of de toelichting bij artikelen wel/niet geprint moet worden.

**Comment by HermanAssink** [comment]
Of de toelichting al of niet is verborgen graag visueel terug laten komen bij knop Toelichting, bijv. door de tekst op de knop te laten wisselen van "Toelichting verbergen" naar "Toelichting tonen" v.v.

**Comment by MaxIDgis** [comment]
In het openstaande pull-request heb ik het volgende gedaan:
![20230704_11h26m16s_grim](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/141267d5-4d9a-451b-aa49-c33c1eb2da0f)
Wanneer de knop ingedrukt is, is de achtergrond dus een stuk donkerder. Ik hoop dat in het bovenstaande plaatje duidelijk is dat toelichtingen "aan" staan en dus getoond worden.
 Is dit OK?

**Comment by MaxIDgis** [comment]
We hebben er nog weer een iteratie overheen gegooid:
![20230705_11h36m02s_grim](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/55b10623-bed8-4723-84e2-f94601f3ec77)
