### ISSUE TITLE
omgevingsplannen van een bepaalde leverancier lijken niet verwerkt te kunnen worden

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#158]
ik heb alle OP's van alle gemeenten van ZH al een tijd geleden gedownload en proberen in te laden.

Enkele lijken niet te verwerken.. de akn lijkt steeds een bepaalde opbouw te hebben waardoor ik denk dat ze van een bepaalde leverancier afkomstig zijn...

/akn/nl/act/gm0505/2023/000197/nld@2023-03-30

/akn/nl/act/gm0523/2022/000004/nld@2022-10-04

etc...

en 1 vreemde/andere qua akn opbouw:

/akn/nl/act/gm1901/2022-09-14/DSB01/nld@10;2022-09-14

Kijk in onze ZH planoview (admin) voor de hele lijst.

**Comment by copierrj** [comment]
Bij de eerste twee omgevingsplannen bevatten de GIOs locaties met id's die geen geldige UUIDs zijn. Het lijken UUID maar dat zijn het niet. (Mogelijk zijn het UUIDs met een 'd' als prefix.) Onze software verwacht op dit moment echter UUIDs en kan daarom de GIOs niet verwerken.

Helaas kan ik in de 'specificatie' nergens terugvinden aan welke voorwaarden deze locatie ids precies moeten voldoen. 

We gaan onderzoeken of we onze software zo kunnen aanpassen zodat we hier arbitraire strings accepteren.

**Comment by copierrj** [comment]
@lamerise kun jij achterhalen welke leverancier het hier betreft?

**Comment by lamerise** [comment]
Ik zie dat het oa dordrecht en h-i-ambacht zijn...

Als ik google op dordrecht en dso software krijg ik dit
https://raad.dordrecht.nl/Documenten/ONGETEKENDE-RIB-Voortgang-implementatie-Omgevingswet-2021-1.pdf

daarin staat:
DSO-software voor plan- en regels en Vth en regelbeheerders
Voor de plan- en regelsoftware hebben we begin van het jaar met de Drechtsteden een
overeenkomst gesloten met de leverancier **Knowledge Values**.

**Comment by copierrj** [comment]
We hebben een issue ingeschoten bij KOOP en antwoord terug gekregen dat onze analyze juist is en dat de softwareleverancier gevraagd gaat worden de getroffen regelingen aan te passen.

**Comment by lamerise** [comment]
gaan ze aan de stelsel kant ook iets doen zodat dit er niet meer in kan komen.. Dat lijkt me beter dan het (alleen) te vragen bij de softwareleverancier... (Wel natuurlijk even een leverancier informeren als je validatie-eisen gaat aanscherpen...
