### ISSUE TITLE
Filtering laat de artikelen/leden die niet zijn geselecteerd niet weg als het bovenliggende structuurelement wel is geselecteerd

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#159]
Voorbeeld:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/8b590eb3-dadd-4f33-a693-d81fe3c69d15)

**Comment by MaxIDgis** [comment]
Stukken dicht laten waarvan de kinderen geen zoekresultaten hebben

**Comment by HermanAssink** [comment]
"Kinderen" zonder zoekresultaten worden niet meer opengeklapt.

**Comment by Brtvrlndn** [comment]
Werkt goed echter:
De functie zelf is nogal omslachtig nl. twee keer klikken: eerst filter aanzetten en daarna zoekresultaten selecteren.
Eén keer klikken zou fijn zijn (met tooltip: Laat alleen zoekresultaten zien in de inhoudsopgave)

**Comment by HermanAssink** [comment]
Dit zijn bewust aparte knoppen/functies omdat het onwenselijk om **altijd** het selecteren en filteren in één klik te doen.

**Comment by HermanAssink** [comment]
Testers zijn het erover eens dat selecteren en filteren niet automatisch in één keer. Wensen mbt look&feel van de filterknop zijn opgenomen in issue #166
