### ISSUE TITLE
Bij het starten van de viewer het planselectievenster openen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#160]
Zodat gebruiker niet eerst het open-icon hoeft te zoeken en te klikken.

**Comment by lamerise** [comment]
ik weet niet in hoeverre het duidelijk is dat als er 1 plan in een groep zit dat het automatisch start...  ik twijfel daar een beetje over..

**Comment by HermanAssink** [comment]
De hint bij het icon voor het openen van een plan is nu verdwenen / wordt niet zichtbaar. Deze graag zichtbaar houden. Bij verplaatsen van dit icon naar de titelbalk is daar wel ruimte voor. Zie ook #151

**Comment by HermanAssink** [comment]
Door het icon te verplaatsen naar de titelbalk is het probleem opgelost
