### ISSUE TITLE
Instellen tot welk niveau inhoudsopgave initieel uitgeklapt moet zijn 

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#162]
Kan per document worden ingesteld met het tandwielknopje. Niet met het penknopje!

**Comment by lamerise** [comment]
ik vind de keuze optie (bediening) nog niet zo intuïtief.. Die van planoview 1 ben ik gewend.

De keuze optie met de fijne pijltjes om te verhogen of te verlagen is lastig te bedienen. Ik zou dan een uitvallende lijst kiezen waar je dan een getalletje uit kan selecteren.. (dan is dan misschien weer logischer dan de vinkboxjes in planoview 1

**Comment by HermanAssink** [comment]
> ik vind de keuze optie (bediening) nog niet zo intuïtief.. Die van planoview 1 ben ik gewend.
> 
> De keuze optie met de fijne pijltjes om te verhogen of te verlagen is lastig te bedienen. Ik zou dan een uitvallende lijst kiezen waar je dan een getalletje uit kan selecteren.. (dan is dan misschien weer logischer dan de vinkboxjes in planoview 1

Met vinkboxjes moet er niet meer dan één gekozen kunnen worden zoals een radio-button

**Comment by copierrj** [comment]
De gekozen input control is een standaard control van de browser en is voor ons het minst bewerkelijk. Wel ontbreekt op dit moment nog validatie: negatieve getallen en niet- getallen worden nu nog toegestaan.

**Comment by MaxIDgis** [comment]
Nu leeft dit onder het penknopje.

Verder is er nog wat verbeterd, je krijgt nu een foutmelding als je een negatief getal of iets anders dan een getal in typt.

Je hoeft overigens niet de kleine pijltjes te gebruiken om het getal te veranderen, je kan het ook intypen.
