### ISSUE TITLE
Inspraakperiode met knop die linkt naar extern formulier instellen.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#163]
Kan per document worden ingesteld met het tandwielknopje. Niet met het penknopje!

**Comment by lamerise** [comment]
lijkt te zitten onder settings/tandwieltje (maar dan staat er boven site), maar ook bij het potloodje in de plansettings.. maar daar werkt submit niet (andere issue)

**Comment by lamerise** [comment]
https://www.zuid-holland.nl

geeft ie als niet valide url.. maar is dat wel

https://www.zuidholland.nl kan dan wel weer (maar dat is niet onze url...)

Blijkbaar staat de invoercontrole wat te streng

**Comment by MaxIDgis** [comment]
Nu maken we gebruik van een beter URL validatie. Je zou nu alle mogelijke URLs in moeten kunnen typen.
