### ISSUE TITLE
Admin: plannen in groepen toevoegen

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#165]
Graag de knoppen opslaan en annuleren verplaatsen naar onder het lijstje "gekoppelde plannen" Dan voeg je namelijk iets toe uit de (bij ons lange lijst plannen die daaronder dan komt te staan)

**Comment by MaxIDgis** [comment]
Is hetzelfde als https://github.com/IDgis/PlanoView2-bevindingen/issues/168
