### ISSUE TITLE
Opmaak en positie filterknop voor compacte weergave inhoudsopgave

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#166]
De look&feel van de filterknop wordt nu als onvoldoende ervaren. Na enige discussie zijn testers het eens om de volgende verbeteringen door te voeren:

1. Filterknop als 1e, vooraan in de rij van open klappen, dichtklappen alles uitzetten zetten
2. Filterknop grijs maken als er niets is geselecteerd in de inhoudsopgave (niet weghalen)
3. Filterknop highlighten zoals de knoppen Selecteer en Verwijder (oranje kader) als de knop actief is
4. Als filter is ingesteld dan beter duidelijk maken dat hier sprake van is. Het ingedrukt zijn van de knop valt nu onvoldoende op.
5. Als hinttekst bij de knop "compacte inhoudsopgave" opnemen
6. Graag een duidelijker icon, bijvoorbeeld een icon met witte binnenkant: 
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/68edfe2a-885a-439c-9222-5a880a952f4d)

**Comment by MaxIDgis** [comment]
Punten 1-5 zijn opgelost
Punt 6 is lastig omdat dat icoon niet in onzet van FontAwesome iconen zit, zie https://github.com/IDgis/PlanoView2-bevindingen/issues/167

**Comment by HermanAssink** [comment]
Punt 3 is nog niet gedaan.

**Comment by HermanAssink** [comment]
Werkt logisch
