### ISSUE TITLE
Icon voor geavanceerd zoeken wijzigen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#167]
Testers denken aan een icon zoals deze:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/c1ca4a9e-4b38-4bf9-a223-4cc53c97fd18)

(combinatie zoeken en instellingen)

**Comment by copierrj** [comment]
Voor ons is het meest praktisch als er een icoontje gebruikt kan worden uit de 'free' set van fontawesome: https://fontawesome.com/search?o=r&m=free

Graag uit deze set het meest geschikte icoontje kiezen.

**Comment by copierrj** [comment]
Suggestie:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2194475/96096cd8-0b51-4f8c-b09e-b18c3c9ca684)

**Comment by HermanAssink** [comment]
Mooi knopje, nodigt uit om op te klikken. Dit "schuifjes"-icon  wordt ook op andere sites gebruikt voor geavanceerd zoeken, bijv. Slack.
