### ISSUE TITLE
In admin de knoppen voor Opslaan en Annuleren naar boven verplaatsen zodat niet ver naar beneden gescrolld moet worden

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#168]
Bijvoorbeeld tussen Gekoppelde plannen en Beschikbare plannen

**Comment by MaxIDgis** [comment]
Ik heb de knoppen op alle paginas in de admin naar boven verplaatst. Hiermee is het (volgens mij) op alle pagina's consistent.
De uitzonderingen op deze regel zijn de koppelpagina's (documenten in groepen, subgroepen in groepen, groepen in sites). Hier staan de knoppen tussen de twee lijsten van items die je kan koppelen.

**Comment by MaxIDgis** [comment]
De knoppen staan nu op alle pagina's rechtsonder in de pagina. Op lange pagina's zouden deze knoppen hier moeten blijven staan en niet uit beeld verdwijnen.

**Comment by HermanAssink** [comment]
Knoppen zijn nu bij lange pagina's buiten beeld:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/200ad720-ef7f-4c98-b7ec-6ce6fcc3bbd2)

**Comment by MaxIDgis** [comment]
Dit is ondertussen gefixed.
![20230704_11h46m16s_grim](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/b297f960-4f28-472b-b6b2-72377d2bddee)
Ik heb meer dan vier plannen geladen en in het bovenstaande plaatje kun je zien dat nu eerst de tabellen ingedrukt worden en de knoppen gewoon in beeld blijven.
Dit werkt overigens op alle pagina's; de knoppen blijven in beeld totdat er geen ruimte meer is voor zowel de titel als de knoppen, dan schuiven ze pas van de pagina af.

**Comment by HermanAssink** [comment]
Beschikbare plannen zijn buiten beeld of de beschikbare plannen zijn wel in beeld, maar de plannen in de groep zijn niet zichtbaar. Voorstel voor de layout: 2. Toon alle plannen in de groep en beschikbare plannen volledig en biedt de mogelijkheid om beide onderdelen gezamenlijk te scrollen, niet ieder afzonderlijk. Nog beter: twee lijsten naast elkaar die je ieder afzonderlijk kunt scrollen. Met deze laatste oplossing wordt de ruimte op het scherm optimaal benut.

**Comment by HermanAssink** [comment]
Werkt goed en ziet er goed uit, ruimte wordt beter benut
