### ISSUE TITLE
Huisstijl Utrecht i.c.m. positie knop Open document

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#169]
Bij Utrecht en mindere mate bij andere provincies, wordt de positie van de knop Open document, aansluitend op het logo, niet fraai gevonden. Cora zal nieuwe  huisstijl van Utrecht mailen. Daarna bezien wat een logische en fraaie plek voor deze knop is.

**Comment by HermanAssink** [comment]
@CoraPU We wachten op de gewijzigde huisstijl van Utrecht voor het oppakken van de deze issue

**Comment by HermanAssink** [comment]
De Open document knop is naar rechts verplaatst. Reden: Doordat de viewer opent met het document-selectie-venster hoeft deze knop niet meer zo prominent in beeld.

**Comment by lamerise** [comment]
De knop voor de link naar een inspraak site komt ook links naast de open knop en dat is niet mooi.. Die moet er rechts naast.
Oplossen icm het toch weer wat verplaatsen de open knop naar links. De Open knop moet de afstand van 1 knop krijgen t.o.v. andere knoppen.

**Comment by HermanAssink** [comment]
![prov_utrecht_zonderwapen2](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/6050e9b1-28f1-4de9-a9ae-c399b2a8f6ad)
Het nieuwe logo van Utrecht.

De kleur voor de rode balk moet zijn #C00D0D (RGB 192/13/13) en hoeft niet meer schuin af te lopen maar kan recht gemaakt worden.
