### ISSUE TITLE
knop resultaat weergeven

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#17]
- knop Resultaat weergeven niet duidelijk aan lijkt uit ? Kleur blauw en grijs omdraaien ?
- bij aanzetten knop resultaatweergeven klappen ook de annotaties open in de inhoudsopgave wordt het erg onoverzichtelijk van. 
- resultaten worden al getoond zonder schuifbalkje aan te zetten als je daarna schuifbalkje aanzet loopt viewer vaak vast. Was 3-november nog niet

**Comment by HermanAssink** [comment]
@CoraPU Hoe kunnen we jouw bevinding "resultaten worden al getoond zonder schuifbalkje aan te zetten" reproduceren/oproepen?

**Comment by AnkeVanBeek-IDgis** [comment]
kleur aangepast, grijs bij niet actief, blauw bij actief

**Comment by CoraPU** [comment]
misschien vergis ik mij maar ik dacht dat de gevonden items in de inhoudsopgave pas oranje highlighten als het balkje resultaat weergeven verschoven werd en niet als er al op het vergrootglas geklikt wordt wat nu wel zo is.  Maar dat is denk ik ook wel goed. 
Bij resultaat weergeven loopt de viewer bij mij nu continue vast.

**Comment by CoraPU** [comment]
is aangepast en knop werkt weer
