### ISSUE TITLE
Ik vind de woorden "site" en "groep" niet zo fraai in de menu's van de groepen etc.. Kan dat ook weg?

### ISSUE THREAD

**Issue by copierrj** [IDgis/PlanoView2-bevindingen#170]
Ik vind de woorden "site" en "groep" niet zo fraai in de menu's van de groepen etc.. Kan dat ook weg?

_Originally posted by @lamerise in https://github.com/IDgis/PlanoView2-bevindingen/issues/148#issuecomment-1602873661_

**Comment by HermanAssink** [comment]
"Groep" en "Site" zijn weggehaald
