### ISSUE TITLE
de titel van de site is nog planoview.. Zou ook de sitenaam mogen zijn...

### ISSUE THREAD

**Issue by copierrj** [IDgis/PlanoView2-bevindingen#171]
de titel van de site is nog planoview.. Zou ook de sitenaam mogen zijn...

_Originally posted by @lamerise in https://github.com/IDgis/PlanoView2-bevindingen/issues/148#issuecomment-1602885277_

**Comment by copierrj** [comment]
De titel is nu per site te configureren:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2194475/0689c431-8512-46ce-81c1-f78dba9dc486)

**Comment by HermanAssink** [comment]
@copierrj Waar komt de dite-naam terug in de viewer?

**Comment by copierrj** [comment]
In de titelbalk

**Comment by HermanAssink** [comment]
In de titelbalk van de browser of het tabblad van het betreffende venster wordt de titel van de site getoond.
