### ISSUE TITLE
zoekvenster linksboven heeft geen functie meer bij geavanceerd zoeken (en werkt dus ook verwarrend).

### ISSUE THREAD

**Issue by copierrj** [IDgis/PlanoView2-bevindingen#172]
zoekvenster linksboven heeft geen functie meer bij geavanceerd zoeken (en werkt dus ook verwarrend). 

suggestie: bij geavanceerd zoeken dit gewone zoekvenster volledig vervangen door het geavanceerde zoekvenster; dit is minder verwarrend en minder druk:

![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/115712307/82111872-1d42-4158-913e-fb8ea83eef20)

_Originally posted by @Brtvrlndn in https://github.com/IDgis/PlanoView2-bevindingen/issues/148#issuecomment-1597185716_

**Comment by HermanAssink** [comment]
Oorzaak van de verwarring is weggenomen en bij geavanceerd zoeken blijft er meer ruimte over voor de inhoudsopagve
