### ISSUE TITLE
Als filter / compacte inhoudsopgave actief dan de knop "Uitklappen" inactief maken (die knop is dan is n.v.t.)

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#175]

**Comment by MaxIDgis** [comment]
Bij actief filter de knoppen "uitklappen" en "inklappen" allebei inactief maken en automatisch uitklappen als de inhoudsopgave ingeklapt is.

**Comment by HermanAssink** [comment]
Uit- en inklappen hebben bij actief filter / compacte weergave betrekking op de "gefilterde" structuurelementen
