### ISSUE TITLE
Knop "Zienswijze indienen" moet tussen Open en Print knop verschijnen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#179]

**Comment by MaxIDgis** [comment]
>De knop voor de link naar een inspraak site komt ook links naast de open knop en dat is niet mooi.. Die moet er rechts naast.
Oplossen icm het toch weer wat verplaatsen de open knop naar links. De Open knop moet de afstand van 1 knop krijgen t.o.v. andere knoppen.
https://github.com/IDgis/PlanoView2-bevindingen/issues/169#issuecomment-1624875850

**Comment by HermanAssink** [comment]
Verschijnt nu op de goede plek
