### ISSUE TITLE
popup scherm 'kaartlagen kiezen'  voorzien van sluiten-icoon

### ISSUE THREAD

**Issue by AnkeVanBeek-IDgis** [IDgis/PlanoView2-bevindingen#181]
Op dit moment is het scherm te sluiten door in het scherm zelf te klikken. Een kruisje rechtsboven (zoals bij bv het selector-scherm) toevoegen.

**Comment by CoraPU** [comment]
kruisje is inderdaad duidelijker. Wij hadden in de huidige viewer een opmerking gekregen over het stukje tekst dat dit onduidelijk is. Kunnen we deze tekst na oplevering  zelf in de beheer omgeving aanpassen ? Of moet er nu een tekstje aangeleverd worden.

**Comment by HermanAssink** [comment]
@CoraPU De test bovenaan het "Open document" venster kun je nu zelf al aanpassen in de beheermodule. Het is de eigenschap Welkomstbericht van de site.

**Comment by HermanAssink** [comment]
klaar
