### ISSUE TITLE
legenda: oogjes vervangen door checkbox

### ISSUE THREAD

**Issue by AnkeVanBeek-IDgis** [IDgis/PlanoView2-bevindingen#182]
De oogje icoontjes ook hier weer vervangen door checkboxes. Is het mogelijk om de selectievakjes alleen te tonen bij het hoveren? Is op die manier de legenda toch ook rustig te houden?

**Comment by CoraPU** [comment]
is inderdaad mooier zo.

**Comment by HermanAssink** [comment]
Afdoende opgelost.
