### ISSUE TITLE
Sluiten pop-up selecteer document(en)

### ISSUE THREAD

**Issue by AnkeVanBeek-IDgis** [IDgis/PlanoView2-bevindingen#183]
Er is geen knop om de selectie via de checkbox(en) te bevestigen, je moet op het kruisje of buiten de pop-up klikken. Moet hiervoor een knop gemaakt worden?

**Comment by HermanAssink** [comment]
zie ook #181

**Comment by MaxIDgis** [comment]
Er zit nu een knopje "Sluiten" in deze pop-up

**Comment by HermanAssink** [comment]
Inderdaad. En het werkt.
