### ISSUE TITLE
gebiedsaanwijzing uitzetten via inhoudsopgave

### ISSUE THREAD

**Issue by AnkeVanBeek-IDgis** [IDgis/PlanoView2-bevindingen#185]
Wanneer je een gebiedsaanwijzing uitzet via inhoudsopgave-annotaties, verdwijnt deze uit de legenda van de kaart. Het zou logischer zijn dat de kaartlaag in de legenda blijft en ‘het oogje’ sluit.

**Comment by HermanAssink** [comment]
Deze wens lijkt me discutabel omdat in de legenda kaartlagen worden getoond die via de inhoudsopgave zijn aangezet
