### ISSUE TITLE
Informatiescherm van documenten

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#189]
In de inhoudsopgave in de viewer staat nu een informatie knopje naast de titel van ingeladen documenten.
Dit knopje opent een scherm met bekende informatie over dat document.

Verder staan hier ook relaties tussen documenten getoond.
Zo kun je bijvoorbeeld in het informatiescherm van een besluit de bijbehorenden regelingen inladen.
Of kun je van een regeling andere versies van die regeling aan en uit zetten.

Als een document niet in een groep aan de site gehangen is, zal deze in het informatie venster van gerelateerde documenten ontbreken.

**Comment by MaxIDgis** [comment]
Over dit document informatiescherm kwamen vanochtend al wat suggesties voor verbetering

### Document informatie
#### Regeling
- Het versienummer van een regeling is vrije tekst en is daarom misschien niet interessant om te tonen. Willen jullie dat dit blijft bestaan of is het beter om weg te laten?
- Het is lastig te onderscheiden welke informatie bij het besluit hoort en welke bij de regeling. Misschien moeten de kolommen andere namen krijgen om dit verschil duidelijker te maken. Er kan ook wat met de tabel zelf gedaan worden, een dubbele scheidslijn tussen de kolommen met regelinginformatie en besluit informatie bijvoorbeeld.
#### Besluit
- De tabel met regeling versies die door dat besluit vastgesteld worden heeft een onduidelijke naam. Nu staat er "Regelingen", misschien is "Dit besluit draagt bij aan de volgende regelingen" beter. Of hebben jullie nog andere ideeën?

### Het zou fijn zijn om linkjes toe te kunnen voegen naar externe pagina's
Zo kan een regelingversie bijvoorbeeld een link krijgen naar de bijbehorende pagina in [officielebekendmakingen.nl](https://officielebekendmakingen.nl). Dit linkje zou dan wel via de admin pagina per document ingesteld moeten worden.

### De volgorde van regelingversies in de versiegeschiedenis klopt vaak niet
Op dit moment gebruiken we de volgende manier om de volgorde van regelingversies te bepalen:
Eerst vergelijken we de datum inwerkingtreding van de regelingversies. Daarna de datum bekendmaking van de besluiten die bij de regelingversies horen. Als we dan nog niet weten welke regelingversie eerder komt, vergelijken we het versienummer van de regelingversies.
Ook met deze werkwijze is de volgorde van regelingversies vaak niet correct vast te stellen. Ten eerste zij de datum inwerkingtreding en datum bekendmaking lang niet altijd bekend in onze testdata.
Ten tweede zij versienummers lastig te vergelijken omdat dit vrije tekst is.
Hierdoor wordt bijvoorbeeld "v13" als een lagere versie gezien dan "v7" wat uiteraard niet klopt.
Een alternatief om dit verhaal deels te omzeilen is om de DSO te bevragen over de volgorde van regelingversies. Of dit op dit moment mogelijk is weten we nog niet en moeten we uitzoeken.

**Comment by HermanAssink** [comment]
Wat betreft volgorde: In de DSO download staat de datum Momentopname/gemaaktOp. Dit is de datum waarop de regelingversie in DSO is geregistreerd. Deze datum kan ook, naast andere data, worden gebruikt voor het bepalen van de volgorde.

**Comment by HermanAssink** [comment]
Is er al iets gedaan met "datum Momentopname/gemaaktOp"? Zo ja, waar kan ik dat zien?

**Comment by HermanAssink** [comment]
Akkoord
