### ISSUE TITLE
Weergave van annotaties in inhoudsopgave verbeteren

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#19]
- beter uitlijnen, schuifbalkje helemaal rechts 
- annotaties standaard niet zichtbaar bij aanklikken artikel 
- groeperen onder kopjes zoals in de pre omgeving DSO ?
- kleurgebruik schuifbalkje bij aan/uit (grijs uit/lichtblauw aan ?), in ieder geval alle schuifbalkjes door viewer heen zelfde kleuren gebruiken.
- alfabetische volgorde zodat volgorde onder locaties gelijk is aan volgorde onder gebiedsaanwijzing
![image](https://user-images.githubusercontent.com/30464824/199997794-d50c8e57-bea5-4bd4-8afe-f728a4a8df19.png)

**Comment by CoraPU** [comment]
alleen groeperen onder kopjes is nog een vraag maar dit staat ook in de issue van Luc de Horde

**Comment by CoraPU** [comment]
Bij visie bij annotaties op 1e regel **tekstdeel** niet weergeven.

Bij verordening bij juridische regel ook adressaat opnemen

**Comment by HermanAssink** [comment]
Zie ook #31

**Comment by copierrj** [comment]
@HermanAssink kan dit issue gesloten worden nu #31 is uitgevoerd?

**Comment by HermanAssink** [comment]
Kan gesloten aangezien #31 akkoord is
