### ISSUE TITLE
Link naar regeling of tijdelijk regelingdeel in besluit bijlage

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#190]
Voor besluiten met regelingen (of tijdelijk regelingdelen) in hun bijlagen:
Als de regeling aan een site gekoppeld is, staat er een link om die regeling te laden in de betreffende bijlage van het besluit.

Als de regeling niet gekoppeld is, zal de link naar die regeling ontbreken.

**Comment by HermanAssink** [comment]
Akkoord
