### ISSUE TITLE
Link naar tijdelijk regelingdeel in regeling

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#191]
Wanneer een regeling een bijbehorend tijdelijk regelingdeel heeft, staat er nu boven in het document de volgende tekst:
"Er gelden hier mogelijk andere regels:"
Met daar onder een link om het bijbehorende tijdelijk regelingdeel te laden.

Hiervoor moet dit tijdelijk regelingdeel wel aan de site gekoppeld zijn.
Indien dit niet zo is, zullen de kop en link missen.

**Comment by MaxIDgis** [comment]
Het kan lastig zijn om van de tekst van een regeling naar de tekst van een bijbehorende tijdelijk regelingdeel te navigeren.
Zeker als je al meerdere documenten open hebt staan en je klikt op de link om een tijdelijk regelingdeel te openen.
Dit tijdelijk regelingdeel opent dan als onderste document en het kan dan best zijn dat dit niet direct onder de bijbehorende regeling komt te staan.
Maar zelfs als de teksten wel direct onder mekaar staan is het lastig om handmatig van de een naar de ander te scrollen.

Een mogelijk idee is om een knop toe te voegen, bijvoorbeeld naast de link naar tijdelijk regelingdeel die het tekstvenster automatisch naar dat stuk tekst scrollt.

Ervaren jullie het als probleem en hebben jullie misschien ideeën?

Dit probleem speelt mogelijk ook bij https://github.com/IDgis/PlanoView2-bevindingen/issues/190

**Comment by HermanAssink** [comment]
Voorstel: hinttest toevoegen aan de link waarmee het document wordt geopend, "Open"-knop toevoegen (als extra aanduiding) en inhoudsopgave scrollen naar het geopende document.
