### ISSUE TITLE
Renvooiweergave van documenten

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#194]
Een document met basismutaties toont deze mutaties als volgt in de viewer
- In de inhoudsopgave staat bij de gewijzigde elementen dat ze gewijzigd zijn.
- In de tekst van dat document staan de wijziginen in renvooiweergave gepresenteerd.

Een document met intergrale tekstvervanging heeft alleen een notitie in de inhoudsopgave dat dat document gewijzigd is. Hier is geen renvooi weergave van bekend.

**Comment by MaxIDgis** [comment]
Uit de testsessie vanochten kwamen wat opmerkingen:
### De gele blokjes die aangeven dat een stuk tekst gewijzigd is zijn niet zo mooi
Hoe zouden we dit mooier kunnen maken?

### Het zou fijn zijn als de renvooi weergave uitgezet kan worden.
Hierdoor is dan de nieuwe toestand van het document te raadplegen zonder bijvoorbeeld hoofdstukken die verwijderd worden of tekst die gewijzigd word.
Dit kan op meerdere manieren gerealiseerd worden: 
- Een gemakkelijke oplossing is een instelling in de admin waarmee de renvooi weergave per document aan of uit gezet kan worden.
- Dit zou afhankelijk kunnen zijn van de datum. Bijvoorbeeld: terwijl een document in de inspraak periode zit wel de renvooi tonen en daarbuiten niet.
Hebben jullie nog andere ideeën?

**Comment by HermanAssink** [comment]
@MaxIDgis: Bovenstaande wensen graag splitsen in aparte issues, zodat we ze apart kunnen prioriteren, ontwikkelen en testen

**Comment by HermanAssink** [comment]
Deze kan gesloten. Detailopmerkingen staan in andere issues.
