### ISSUE TITLE
In de viewer, hoe maken we duidelijk of een document een besluit of een regeling is

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#195]
In de test sessie vanochtend werd het duidelijk dat het best lastig kan zijn om te zien of een geopend document een besluit of een regeling is.
Dit is bijvoorbeeld zeker een probleem als een besluit en de bijbehorende regeling dezelfde naam hebben en allebei geopend zijn.
Hoe kunnen we duidelijk maken aan de gebruiker welke tekst bij het besluit hoort en welke bij de regeling.

Een suggestie van Evert-Jan was om symbolen te gebruiken: een kroon voor regelingen en een hamer voor besluiten.
Misschien kan ook gewoon de tekst "besluit" en "regeling" klein naast de titel neergezet worden.

Wat hier precies handig is weten we niet echt.

Mij lijkt het sowieso handig om iets in het tekstvenster neer te zetten dat dit verschil aanduid, maar misschien moet de inhoudsopgave ook nog extra indicatie geven.

Wat vinden jullie?

**Comment by HermanAssink** [comment]
Mijn voorstel: Het type document (besluit/regeling/tijdelijk regelingdeel) opnemen achter de titel in de inhoudsopgave, in aanvulling op een icon voor het type document vóór de titel .

**Comment by HermanAssink** [comment]
@MaxIDgis : Zoals besproken op alle plekken in de viewer, o.a. het info-venster, de icons en typenaam opnemen

**Comment by MaxIDgis** [comment]
De combinatie icoon + typenaam staat nu op alle relevante plekken in de viewer.
Verder zijn de icoontjes ook op alle locaties toegevoegd in de admin.

**Comment by MaxIDgis** [comment]
Er is toch nog een locatie in de admin waar de icoontjes missen.
Bij het aanmaken van een nieuwe groep kunnen er documenten geselecteerd worden. Hier staat alleen een type bij en nog geen document icoon.
Dit gaat gerepareerd worden.

**Comment by HermanAssink** [comment]
Duidelijk
