### ISSUE TITLE
Renvooi weergave voor een document uit kunnen zetten

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#197]
Hiermee is de nieuwe toestand van het document te raadplegen zonder bijvoorbeeld hoofdstukken die verwijderd worden of tekst die gewijzigd word.
Dit kan op meerdere manieren gerealiseerd worden:
- Een gemakkelijke oplossing is een instelling in de admin waarmee de renvooi weergave per document aan of uit gezet kan worden.
- Dit zou afhankelijk kunnen zijn van de datum. Bijvoorbeeld: terwijl een document in de inspraak periode zit wel de renvooi tonen en daarbuiten niet.

Hebben jullie nog andere ideeën?

**Comment by MaxIDgis** [comment]
Er is een knopje toegevoegd die renvooi weergave aan en uit zet.
Dit knopje staat tussen de filter knop en de "klap alles open" knop
Standaard staat dat knopje op aan.

**Comment by HermanAssink** [comment]
@MaxIDgis Het nieuwe knopje heeft een ander gedrag dan de filterknop, terwijl beide knoppen een vergelijkbare functie hebben. Daarom is mijn voorstel: Gebruik alleen de icon met pen. Bij ingedrukt wordt het renvooi getoond bij niet ingedrukt wordt renvooi niet getoond.

**Comment by MaxIDgis** [comment]
Dit is gecorrigeerd.
Nu is de knop grijs als er geen renvooi in de geladen documenten zitten.
Verder is de knop actief of inactief, aangegeven doordat de knop "ingedrukt" of niet "ingedrukt" is.

**Comment by HermanAssink** [comment]
Akkoord
