### ISSUE TITLE
Waarom geen GIO in de tekst van Zeeland?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#200]
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/c9dd5a84-d83a-4a8c-87ff-013eb98c2edd)

Het gaat om het beheergebied brandganzen.

deellink: https://test.viewer.planoview2-demo.idgis.eu/mutaties?s=d9f05064-e2e5-4b80-8c8d-1ef0be511212

**Comment by copierrj** [comment]
Het lukt mij niet om dit te reproduceren, 'beheergebied brandganzen' is bij mij lokaal correct verwerkt:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2194475/75e77066-b906-48e0-ab37-ce4729839bd6)

**Comment by HermanAssink** [comment]
Is opgelost na opnieuw importeren
