### ISSUE TITLE
Automatisch afmaken URL op nieuwe service toevoeg pagina

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#201]
Op de admin pagina waar een nieuwe service ingesteld kan worden is de functionaliteit iets aangepast:
In het URL veld moest de gebruiker de URL beeindigen met een "?" (of soms een "&") symbool om de service correct aan te roepen vanuit Planoview.
Nu hoeft dat niet meer, indien nodig wordt het juiste symbool automatisch achter de URL geplakt. Je mag het "?" symbool nog steeds handmatig invoeren.

Helaas staat er op de testservice nog wel een incomplete variant hiervan. De URL wordt alleen achter de schermen afgemaakt en ook alleen bij het opslaan van de nieuwe service. Het knopje om de service te testen werkt nog alleen als de URL op de voormalig juiste manier is ingevuld.

Er komt heel binnenkort nog een verbetering hiervan op de testomgeving:
De URL wordt visueel aangepast zodat de gebruiker ziet wat de uiteindelijke URL wordt.
Het test service knopje werkt met de aangepaste URL, waardoor het gedrag van deze knop hetzelfde is als wanneer de service opgeslagen wordt.

**Comment by HermanAssink** [comment]
Werkt
