### ISSUE TITLE
Veranderde weergave van URL op service overzichtpagina

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#202]
Op de admin pagina waar alle ingestelde services te zien zijn is de weergave van de URLs aangepast:
Eerst werd hier de URL weer gegeven zoals die in de database opgeslagen is, maar nu wordt de URL afgemaakt tot een getCapabilities request.

Dit betreft alleen de weergave op deze pagina. Als je de URL van een service gaat aanpassen dan zie je niet het getCapabilities gedeelte.

**Comment by HermanAssink** [comment]
OK
