### ISSUE TITLE
Bugfix WMS services

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#203]
De WMS server van Brabant triggerde twee bugs in onze code.
Eentje waardoor WMS lagen van hun service niet correct opgeslagen werden.
En eentje waardoor de lagen niet zichtbaar werden in de viewer.

Deze twee bugs zijn gefixed.

Dit kan getest worden met de volgende URL: https://atlas.brabant.nl/ArcGis/services/OVR_Natuur_stiltegebied/MapServer/WMSServer

**Comment by HermanAssink** [comment]
gefixt
