### ISSUE TITLE
Filterknop onduidelijk

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#204]
Als er bij een document maar 1 filter is om aan en uit te zetten is het niet duidelijk welk filter dat is. Dit moet duidelijker worden.

De gesuggereerde optie is om iets slims te doen met de tooltip van de filter knop.

**Comment by HermanAssink** [comment]
Kan de tooltip worden aangepast aan de situatie: filteren op renvooi, op kaart of één van beide?
