### ISSUE TITLE
Gezochte woorden worden niet overal gevonden/weergegeven in de tekst

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#21]
aantal zoektermen geprobeerd gaat niet altijd goed (zowel de verordening als de visie staan aan) een paar voorbeelden

- grondwaterbescherming waarom alleen toelichting artikel 10.18 en niet de rest bv artikel 3.5 uit de verordening
- Bij luchtvaart gaat het ook niet goed vindt alleen de divisietekst bij een bijlage uit de verordening en de termen in de visie en niet luchtvaartterein uit artikel 4.65 en 4.66 uit de verordening.

Daarnaast wordt bij zoeken van een dubbel woord (bv groene contour) ook alle losse woorden getoond bij resultaat. Is dit wenselijk ?

zoals ook al vermeld bij knop resultaat weergeven lijkt er na de laatste update iets niet goed te gaan bij zoekopdracht. resultaten worden al getoond voordat knop is aangezet en de viewer loopt vast.

**Comment by HermanAssink** [comment]
Is dit probleem nu opgelost doordat er bij het zoeken suggesties worden getoond?

**Comment by Brtvrlndn** [comment]
Hij vindt niet alle termen in de tekst, bijv. met "water" zou je ook "grondwaterbeschermingsgebieden" willen vinden in de tekst. Bovendien onduidelijk wat het verschil is tussen de gewone zoekfunctie en de geavanceerde zoekfunctie zoek op woord(en) 
Suggestie: de gewone zoekfunctie met suggestielijst (zoals nu is) en de geavanceerde zoekfunctie aanvullen / vervangen door fuzzy search. of andersom
Ook nog dit: s.v.p. help tekst in geavanceerd zoekveld aanvullen: Zoek op woord(en) **in de tekst**

**Comment by lamerise** [comment]
is beter geworden. Kan wat mij betreft gesloten...

**Comment by HermanAssink** [comment]
@CoraPU : Wil jij controleren of dit issue gesloten kan worden?

**Comment by CoraPU** [comment]
Je kunt niet op 2 woorden zoeken ? bv **groene contour** daar wordt dan **groene**  van gemaakt en vervolgens wordt ook bv groenonderhoud gevonden.
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/30464824/d2d28b0d-1d12-4c1b-b304-16286de8c070)

**Comment by Brtvrlndn** [comment]
Zoeken gaat nog niet altijd goed
Bijvoorbeeld: zoeken op "zone" levert bij ons in de verordening niet altijd alle hits op (annotatie in tekst wel maar term in artikelnaam niet:

![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/115712307/7bdbdd47-3730-4e60-b0ac-e54ebbe3ae26)

**Comment by HermanAssink** [comment]
In sommige gevallen, bijv "berekenen oppervlaktecompensatie", worden bij het 2e woord geen suggesties meer getoond. Ook gezien bij het 3e woord, bijv "groene contour worden" (getest met verordening Utrecht)

**Comment by HermanAssink** [comment]
Je kunt nu op meerdere woorden zoeken
