### ISSUE TITLE
Nieuwe workflow bestanden uploaden

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#212]
![Uploads pagina](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/66d69b1b-9bae-47ec-b2fe-1272cd37cca8)

Bij het uploaden van een document opent een venster met de voortgang van de upload. Zodra de upload klaar is worden de documenten in die upload getoond:
![successful_upload](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/19a5f1fe-2f52-4f57-9745-9102b1d48485)

Op dit moment wordt er nog niks gedaan met die documenten, om ze in PlanoView te laden moet er op de knop "importeren" gedrukt worden.

Als het venster per ongeluk gesloten is, kunnen de documenten alsnog geimporteerd worden door op het "documenten" knopje te klikken in de tabel met uploads. Op deze pagina kan per document op het importeer knopje gedrukt worden of kunnen alle document in een keer geimporteerd worden door te klikken op het knopje "Alle documenten importeren":

![upload_documents_not_imported](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/d9c9a39f-6fc4-4040-b3c9-295072ab400c)

![upload_documents_imported](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/79f48e46-94c0-4767-8b39-1eadd7e03a56)

Pas zodra een document geimporteerd gaat worden/geimporteerd is, is dit document zichtbaar op de "Documenten" pagina.

Als er bij het uploaden een fout optreedt of een actie vereist is om de documenten successvol te kunnen importeren, opent het volgende venster:

![mutation_uploaded](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/23758def-d98f-4c9f-9c35-7dc3c494c75a)

In dit geval heb ik een mutatie document geupload en moet een voorgaande versie geselecteerd worden voordat de documenten geimporteerd kunnen worden. Als ik dan op de knop "Selecteer upload met voorgaande versie" klik, opent het volgende venster:

![mutation_select_previous_upload](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/555f0909-288a-4c1f-bd8d-66028eddd573)

Hier zien we dat er al een upload gemaakt is met de vorige versie van het document. Als ik die upload selecteer en op de "Selecteer" knop druk dan is de upload successvol afgerond en opent het venster van een successvolle upload:

![mutation_successful](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/a28b5c62-7d67-468d-b8af-11770c9301a7)

Als ik nog geen upload met een vorige versie beschikbaar heb, dan zie het volgende in "selecteer vorige versie" venster:

![mutation_no_previous_document_found](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/378c31c4-ece8-486f-8d65-8339984bb21a)

In dit geval moet het venster gesloten worden en de vorige versie geupload worden. Om het venster weer opnieuw te openen, kan op het gele knopje bij de upload gedrukt worden:

![mutation_has_exception](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/9ac1854f-1239-4f4a-b70c-bf36d85b85c1)

Zodra de upload met voorgaande versie voltooid is, kun je het venster weer openen en de vorige upload selecteren zoals eerder getoond is.

Als er op het verwijder knopje van een upload gedrukt wordt, opent er een waarschuwingsvenster met de documenten die bij die upload horen. Als de upload verwijderd worden, dan worden deze documenten ook verwijderd:

![delete_upload](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/4947ab6c-e927-4a48-9c72-1762836a0b54)

**Comment by HermanAssink** [comment]
Akkoord
