### ISSUE TITLE
De zip uit Tercera Go! met daarin de Omgevingsverordening upload niet naar de viewer

### ISSUE THREAD

**Issue by DennisvanMier** [IDgis/PlanoView2-bevindingen#213]
In tercera Go! kan de versie die op de pre-omgeving staat gedownload worden als zip-file. Als ik die probeer te uploaden staat er: Er is iets mis gegaan bij het uploaden. Ik stuur de zip-file naar Reijer en Herman via wetransfer.

**Comment by copierrj** [comment]
De zip bevat een mutatielevering van het type intergrale tekstvervanging. Mutatieleveringen kunnen enkel verwerkt worden als ook de eerdere levering beschikbaar zijn. In de huidige versie is de ondersteuning van mutatieleveringen nog beperkt, maar deze functionaliteit is in de volgende versie verder uitgewerkt.  Kun je ons ook de eerdere leveringen sturen? Dan kunnen we deze (o.a.) gebruiken als testdata.

**Comment by DennisvanMier** [comment]
Ah ja, logisch, Even voor mijn beeldvorming; Als we een nieuwe wijziging van onze Omgevingsverordening weer willen geven in de viewer, moeten we dan de initiële Omgevingsverordening erin uploaden als pakketje vanuit Tercera en alle opvolgende wijzigingen plus diegene die we weer willen geven? Of kunnen we ook de geldende versie vanuit het DSO downloaden (waarin alle wijzigingen verwerkt zijn), deze uploaden en alleen de laatste wijziging daarop als Tercera pakketje (die nog niet in het DSO staat)?
Ik heb een nieuw pakketje verstuurd via wetransfer met daarin hopelijk de juiste versie.

**Comment by copierrj** [comment]
De downloads (maar ook output van plansoftware in het plan-plan uitleverformaat) zijn consolidaties en kunnen daardoor altijd los ingelezen worden. Deze zipjes bevatten echter enkel de regels en niet het besluit. Ook kennisgevingen ontbreken. 

Om een regeling dmv LVBB leveringen te importeren zijn altijd alle LVBB leveringen voor deze regeling nodig. Dit levert een completer beeld op in PlanoView dan het importeren vanuit het uitleverformaat.

**Comment by DennisvanMier** [comment]
Ok, duidelijk, bedankt voor het snelle antwoord.
