### ISSUE TITLE
Kenmerken groepering

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#214]
In het venster zoeken op kenmerken zijn activiteiten en gebiedsaanwijzingen gegroepeerd:
![kenmerkengroepering](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/583f5a14-7f2f-4b05-b86d-f552a3778c1f)

**Comment by HermanAssink** [comment]
voorlopig akkoord
