### ISSUE TITLE
Stijlen van bepaalde koppen (waarschijnlijk H3,H4,H5) in vooral programma en visie (vrije tekststructuur) meer onderscheidend maken.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#217]
![image003](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/cdbe6683-d65b-408f-ad70-de1d8fb3dee8)

**Comment by copierrj** [comment]
Resultaat:

![image](https://github.com/IDgis/PlanoView2/assets/2194475/4965b386-f67b-46a2-b34d-6e5107deb112)
