### ISSUE TITLE
Bij het toevoegen van documenten datum iwt en/of datum upload laten zien zodat de naam van het document niet aangepast hoeft te worden maar je toch versies uit elkaar kunt houden

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#218]
Hieronder kun je bijvoorbeeld zien dat de naam is aangepast zodat je in de rechter lijst verschillende versies van dezelfde regeling uit elkaar kunt houden. Een betere oplossing is het opnemen van kenmerken zoals datum iwt en/of datumtijd upload zodat je versies uit elkaar kunt houden. De bij Max onderhanden versie van dit venster is misschien al een oplossing. Dat moeten we even bekijken.

![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2979044/dc220e36-dd54-4df7-a00e-8ece9e3b2e71)

**Comment by MaxIDgis** [comment]
![AddToGroup](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/107a7e33-7d2f-4f01-84ed-3811abdc1683)

Hier een screenshot van de nieuwe layout van hetzelfde scherm.
We hebben een extra kolom met de datum en tijd van upload toegevoegd.
Aangezien dit de tabel een stuk breder maakt, hebben we ervoor gekozen om de layout van zij-aan-zij naar boven en onder te veranderen.

De vraag is nu dus of dit het inderdaad gemakkelijker maakt om documenten uit elkaar te houden en of dit een goeie layout is voor dit venster.

**Comment by HermanAssink** [comment]
Dit is zo te zien voldoende. Kan worden getest.
