### ISSUE TITLE
Omgevingsnormen en Omgevingswaarden

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#219]
Er is nu ondersteuning gebouwd voor het tonen van omgevingsnormen en omgevingswaarden.

In het zoeken op kenmerken venster zijn nu nieuwe tabbladen toegevoegd. In een document met omgevingsnormen zie je het tabblad "omgevingsnorm", in een document met omgevingswaarden verschijnt ook een tabblad voor "omgevingswaarde".
Een voorbeeld met omgevingswaarden volgt later.
![kenmerken](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/0673131d-f3c5-4906-969f-e6d3a1adacac)

Als een omgevingsnorm geselecteerd wordt in het zoekvenster zien we zoals gewoonlijk het tekstdeel waar deze omgevingsnorm voorkomt.
![searchResult](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/012ffe65-12f7-43f7-8b72-d6814f0ba760)

De omgevingsnorm kan aangezet worden door op de "selecteer" knop te drukken in het zoekpaneel, maar dit kan ook met de hand gedaan worden door de annotaties bij het bijbehorende tekstdeel open te klappen en het schuifje van de omgevingsnorm zelf aan te zetten.
![annotaties](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/3a1d8190-2e5a-422c-a0ab-2823baab41a2)

Als een omgevingswaarde aan staat, ziet dat er zo uit
![omgevingswaarde](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/9a6baa20-5ae0-4725-bdee-8e7c948c8025)

Hier is het kenmerken venster van een document met zowel omgevingsnormen en omgevingswaarden.
![kenmerken2](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/cf3f421b-b1d4-4b74-af0f-06173a8a144c)

Een omgevingswaarde wordt op dezelfde manier aangezet als een omgevingsnorm en ziet er hetzelfde uit.
![omgevingswaarde](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/9d163392-0e23-4bd0-bb1a-717b8e63937e)

Omgevingsnormen en omgevingswaarden kunnen net zoals normale kaartlagen bediend worden in de legenda. Hier zijn omgevingsnormen en omgevingswaarden te herkennen aan de tekst "abc" in de kaartlaag preview.
![legend](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/82172dc7-9550-4a4f-9849-b9be6bf75279)

**Comment by HermanAssink** [comment]
Akkoord
