### ISSUE TITLE
titel in tekst verschil in hoogte bij gebruik paragraaf/subparagraaf

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#22]
Verschil in letter hoogte van titels artikel en lid in de tekst  bij gebruik van paragraaf/subpagraaf.  Artikelen en leden altijd dezelfde letter hoogte voor de leesbaarheid. vooral bij subparagraaf krijgt het artikel nu wel een heel klein lettertype

![image](https://user-images.githubusercontent.com/30464824/200006626-b859db63-4d1a-4024-acb8-14cc90783c0e.png)

**Comment by CoraPU** [comment]
Gaat nog niet helemaal goed Artikel is niet altijd vetgedrukt (bv hfdstk 1) en subparagraaf is wel vet maar paragraaf niet. Alles Vet maken ?

**Comment by CoraPU** [comment]
Het Lijkt erop dat als een artikel direct onder een afdeling staat dat dan de opmaak niet goed gaat, niet vetgedrukt en geen wit regel tussen artikel en lid.
ook paragraaf is niet vetgedrukt onder afdeling

Graag lid nummers kleiner zelfde letter grootte als de tekst erachter wel vetgedrukt.

**Comment by TitiaBaeten** [comment]
![image](https://user-images.githubusercontent.com/119037891/205246057-a7272a52-0e64-4276-acd2-c01152eeb29d.png)
