### ISSUE TITLE
Gemaakt op bij plan-plan uitwisselingen

### ISSUE THREAD

**Issue by MaxIDgis** [IDgis/PlanoView2-bevindingen#220]
Bij plan-plan uitwisselingen (geen lvbb aanleveringen) is het attribuut "Gemaakt op" inzichtelijk gemaakt in het document informatie venster.
![gemaaktOp](https://github.com/IDgis/PlanoView2-bevindingen/assets/126654128/630565f3-96cb-4983-90d6-59b2681178a5)

**Comment by HermanAssink** [comment]
Weergave van "Gemaakt op" en "Datum bekendmaking" nu onduidelijk. Als er sprake is van een plan-plan uitwisseling dan bij "Datum bekendmaking" de waarde "Niet beschikbaar" weergeven. Niet beide typen datum velden in dezelfde kolom weergeven, maar in aparte. Veldnaam "Gemaakt op" is ook onduidelijk, voorstel: wijzigen in "Download van" [Zie het voorbeeld](https://www.figma.com/file/wL2ctk2ymhsqExneRUb9XB/IDgis-%2F-Planoview?type=design&node-id=0%3A1&mode=design&t=wZTnNg3rqvmZVqxt-1)

**Comment by HermanAssink** [comment]
Opmerking Evert-Jan: Ik denk  dat je voor externe raadplegers “gemaakt op” wel willen kunnen verbergen.. Het is namelijk niet relevant.. Het is alleen voor jezelf van belang indien een plan geen iwt/bekendmaking datum heeft.
Ik denk dus dat we het niet standaard moeten laten zien.
Het zou een vulling kunnen zijn als er geen iwt/bekendmaking datum zijn (maar dat moet dan wel duidelijk zijn dat dit een alternatieve invulling hiervan is.
Dus wat mij betreft geen standaard kolom “gemaakt op”. Of uiteindelijk een optie om dit in die gevallen waar het relevant is dit in te vullen via de admin.

**Comment by HermanAssink** [comment]
Deze kan gesloten worden want er komt een wijziging van de standaard om versies van annotaties (imow) te kunnen onderscheiden.
