### ISSUE TITLE
tekst onder beschikbare documenten in het selecteer documenten venster aanpassen

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#221]
tekst onder beschikbare documenten is niet in de beheermodule aan te passen. 

Kan deze tekst aangepast worden naar:

Door op de naam van het document te klikken, wordt het desbetreffende document direct geopend.  Wilt u meerdere documenten bekijken, gebruik dan de selectievakjes en klik vervolgens op de knop Sluiten.

**Comment by HermanAssink** [comment]
Done
