### ISSUE TITLE
link naar locatie in bijlage

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#222]
Link naar locatie in bijlage vanuit de tekst werkt bij mij niet altijd goed. 

De link gaat niet naar de bijlage maar krijg wel de melding ga terug naar artikel..
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/30464824/839a41ee-142e-4170-9f62-649a75064f5b)

En soms gaat die wel naar de bijlage maar dan werkt de link ga terug niet meer.

**Comment by HermanAssink** [comment]
fixed
