### ISSUE TITLE
Het al of niet  groeperen van kenmerken op type&groep configurabel maken per document

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#226]
Nadeel van de groepering is dat de kenmerken niet alfabetisch gesorteerd zijn.

**Comment by copierrj** [comment]
Dus dit:

![image](https://github.com/user-attachments/assets/a05a24f0-f251-41a7-b03e-23c726757a0b)


ipv dit:

![image](https://github.com/user-attachments/assets/0e36ad4f-1974-444c-ba7b-212f63d83998)

?

**Comment by HermanAssink** [comment]
Dit is wat er m.i. wordt bedoeld. Zou je dit kunnen regelen met een vinkje bovenaan in dit formulier?

**Comment by copierrj** [comment]
![image](https://github.com/user-attachments/assets/df6aa07e-cb71-4f78-b05e-ef12c42a7388)

Zoiets?

En dan verder configurabel maken niet meer nodig?

**Comment by HermanAssink** [comment]
Wat mij betreft prima. En dan is configurabel maken niet nodig.
