### ISSUE TITLE
Document informatie (i) knop geeft foutmelding

### ISSUE THREAD

**Issue by Brtvrlndn** [IDgis/PlanoView2-bevindingen#227]
Als ik op de de document informatieknop klik (i) dan krijg ik melding: De applicatie is gecrashed (herstarten)

**Comment by copierrj** [comment]
De viewer crashed omdat er geen waarde beschikbaar is voor het veld 'gemaaktOp'.

**Comment by Brtvrlndn** [comment]
In de testomgeving werkt het wel goed met hetzelfde plan> De viewer crashed omdat er geen waarde beschikbaar is voor het veld 'gemaaktOp'.

kan dit knopje weg totdat dit is opgelost

**Comment by HermanAssink** [comment]
In de testomgeving werkt het doordat daar ook het besluit is geladen in de groep. Dus als je het besluit / de besluiten ook in de productie laadt in de groep dan is het probleem opgelost. Verder komt er een fix aan waarbij de applicatie niet meer crasht in zo'n geval.

**Comment by HermanAssink** [comment]
Is verholpen
