### ISSUE TITLE
Kopjes in besluit 

### ISSUE THREAD

**Issue by copebo** [IDgis/PlanoView2-bevindingen#228]
Bij een besluit worden allerlei kopjes getoond, denk aan 'Opschrift', 'Aanhef', 'Sluiting' en 'Ondertekening'. In de landelijke voorziening (Officiële bekendmakingen) worden de kopjes 'Aanhef' en 'Slotformulier en ondertekening' wel in de inhoudsopgave getoond, maar niet in de content. 

Het lijkt ons vanuit Provincie Zuid-Holland dan ook verstandig om dit gelijk te trekken met de Officiële bekendmakingen zodat de weergave van de besluiten gelijk is.

Dit zou inhouden voor het contentscherm (rechts onder de kaart):
1. Het opschrift als header tonen (al is dat misschien overbodig, omdat deze al bovenaan de content staat. Omdat in de inhoudsopgave het niveau 'Besluit' link naar het kopje 'Opschrift' zie je die titel niet)
2. Aanhef zonder kopje laten zien
3. Artikelen zijn prima zo
4. Sluiting zonder kopje laten zien
5. Ondertekening ook zonder kopje laten zien

Dit zou inhouden voor de inhoudsopgave:
1. Opschrift laten vervallen als optie in de inhoudsopgave

![CleanShot 2024-04-09 at 11 17 57@2x](https://github.com/IDgis/PlanoView2-bevindingen/assets/54364210/cc2c248d-298f-4681-a62a-78a490f3e305)
![CleanShot 2024-04-09 at 11 17 20@2x](https://github.com/IDgis/PlanoView2-bevindingen/assets/54364210/2562c09c-07cf-48e8-9a00-e4053739ca34)

**Comment by copierrj** [comment]
De koppen 'Opschrift', 'Aanhef',  'Sluiting' en 'Ondertekening' kunnen eenvoudig worden weggehaald. 

Het weglaten van structuurelementen (zoals 'Opschrift') in de inhoudsopgave is niet mogelijk. Dit heeft te veel impact op de werking van de programmatuur.

We zullen de opmaak van het besluit vergelijken met officiële bekendmakingen en PlanoView zo veel mogelijk hiermee in lijn brengen.

**Comment by lamerise** [comment]
Ik vind opschrift nog steeds heel storend. Kan dat dan toch niet weggelaten worden door iets slims te doen

**Comment by HermanAssink** [comment]
Kopjes zijn weg uit de tekst. Wens is om deze optioneel ook weg te laten uit de inhoudsopgave. Zie #233
