### ISSUE TITLE
Toevoegen mogelijkheid om een url naar toegankelijkheidsverklaring op te nemen in PlanoView

### ISSUE THREAD

**Issue by copierrj** [IDgis/PlanoView2-bevindingen#230]

**Comment by copierrj** [comment]
In de admin kan nu bij een site een url naar een toegankelijkheidsverklaring opgenomen worden. Deze komt dan in de viewer terug als knop in de titelbalk.

Admin:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2194475/a17d02db-11bf-4983-a6cb-dd0283e173bd)

Viewer:
![image](https://github.com/IDgis/PlanoView2-bevindingen/assets/2194475/9f1cfaf3-a07c-4e75-8ef4-ae62237fe07c)

**Comment by HermanAssink** [comment]
Is toegevoegd. Bij ontbreken contact-url wordt het betreffende knopje nu weggelaten
