### ISSUE TITLE
Annotaties niet automatisch open klappen in inhoudsopgave als artikel/lid/divisie/divisietekst wordt aangevinkt

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#24]
Automatisch open klappen van annotaties geeft een onoverzichtelijke inhoudsopgave.
Annotaties alleen open klappen als op het label icoontje wordt geklikt, dus niet bij klikken op knop "Resultaat weergeven" en aanvinken van structuurelement.

**Comment by CoraPU** [comment]
getest en werkt
