### ISSUE TITLE
Artikelgewijze toelichting springt niet in obv hoofdstuk/afdeling/paragraaf etc.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#27]
Voorbeeld:
![image](https://user-images.githubusercontent.com/2979044/200322218-2cfcdccd-7d6e-4875-98fc-b06275929381.png)

Structuurelementen van toelichting laten inspringen zoals bij Omgevingsvisie.

**Comment by copierrj** [comment]
Dit blijkt te komen doordat deze informatie 'plat' in de STOP xml zit.

@KevinvdBosch weet jij zo of dit aan de STOP kant op te lossen is?

**Comment by KevinvdBosch** [comment]
In de toelichting (zowel algemene als artikelsgewijze) wordt het vrije tekstmodel gebruikt. Hierin kunnen divisies en divisieteksten genest worden. In STOP zou het op te lossen zijn door de structuur ook netjes te nesten in plaats van zo plat aan te leveren

**Comment by HermanAssink** [comment]
Heb ik het goed begrepen dat het probleem is op te lossen door de structuur goed genest aan te leveren en het dan automatisch goed gaat? Zo ja, kan dan dit issue worden gesloten?

**Comment by HermanAssink** [comment]
Moet opgelost worden in de content
