### ISSUE TITLE
doorlopen zoekresultaten in inhoudsopgave

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#29]
Als je in de inhoudsopgave op een gehighlight zoekresultaat klikt wil je eigenlijk dat de tekst hiernaar verspringt. Nu moet je dubbelklikken. De eerste keer zet je het artikel uit, de tweede keer zet je het artikel weer aan en ga je ook naar de bijbehorende tekst in het tekstvenster. 

Binnen een zoekresultaat wil je eigenlijk dat je met één klik in de inhoudsopgave meteen ook de tekst ziet in het tekstvenster

**Comment by copierrj** [comment]
Het werkt nu als volgt:

Een artikel wat nog niet aan staat is aan te zetten door het artikel aan te klikken in de inhoudsopgave. Het maakt daarbij niet uit er wordt geklikt op de titel van het artikel of op de checkbox.

Het klikken op een titel van een artikel dat reeds aan staat heeft scrollen naar dit artikel tot gevolg. 

Om een artikel dat aanstaat uit te zetten is het noodzakelijk dat er op de checkbox geklikt word.

**Comment by CoraPU** [comment]
getest en dit werkt prettiger
