### ISSUE TITLE
zoekfunctie

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#30]
bij nieuw zoekopdracht zonder knop verwijder selectie te gebruiken wordt wel de nieuwe zoekopdracht gehighlight in inhoudsopgave maar de oude zoekopdracht blijft nog aangevinkt staan en gehighlight in de tekst.   Bij nieuwe zoekopdracht automatisch oude zoekopdracht laten verwijderen ?

![image](https://user-images.githubusercontent.com/30464824/200583799-8975de1f-e27b-4abd-9946-098c57da1116.png)

![image](https://user-images.githubusercontent.com/30464824/200584411-d47b9597-9995-4192-9ca6-ff4a79ee45b5.png)

**Comment by CoraPU** [comment]
Het gaat nu goed dat het schuifbalkje uitgezet wordt bij nieuwe zoekopdracht en dus niet meer in tekst gehighlight is. In de inhoudsopgave blijven alleen de items van de eerdere zoekopdracht aangevinkt staan (highlight gaat wel uit) deze moeten ook nog uitgezet worden

**Comment by HermanAssink** [comment]
Is opgelost
