### ISSUE TITLE
annotatieduiding

### ISSUE THREAD

**Issue by LucdeHorde** [IDgis/PlanoView2-bevindingen#31]
over het weergeven van annotaties is ondertussen uitgebreid afgestemd voor de landelijke viewers; sluit hierbij aan, zie plaatje
![afbeelding](https://user-images.githubusercontent.com/58255396/200588533-e2bb9d57-719c-48b9-8be0-f447df237458.png)

**Comment by HermanAssink** [comment]
@LucdeHorde : Weet jij voorbeelden van regelingen op de pre-omgeving met omgevingsnormen, -waarden en kaart-annotaties?

**Comment by LucdeHorde** [comment]
Hoi Herman

In Amsterdam (Buiksloterham) is geannoteerd met normen:
***@***.***

Van: Herman Assink ***@***.***>
Verzonden: vrijdag 11 november 2022 08:46
Aan: IDgis/PlanoView2-bevindingen ***@***.***>
CC: Luc de Horde ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [IDgis/PlanoView2-bevindingen] annotatieduiding (Issue #31)


@LucdeHorde<https://github.com/LucdeHorde> : Weet jij voorbeelden van regelingen op de pre-omgeving met omgevingsnormen, -waarden en kaart-annotaties?

**Comment by copierrj** [comment]
Er staat een versie klaar die meer aansluit bij de landelijke viewers.
