### ISSUE TITLE
hyperlink begrip

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#32]
onduidelijk voor de gebruiker wat voor link dit in de tekst is. Map tip toevoegen met ga naar uitleg begrip o.i.d..  Nog mooier om de uitleg van het begrip in een maptip op te nemen zodat er niet meteen doorgeklikt hoeft te worden.

![image](https://user-images.githubusercontent.com/30464824/200588768-e582aef0-a02f-437d-912a-6ed056ac92dd.png)

**Comment by HermanAssink** [comment]
In STOP is er geen verschil tussen een link naar een begrip en een link naar een andere paragraaf. Hoe maken we het verschil?

**Comment by lamerise** [comment]
achterhalen of het een begrip is uit de bijlage en dan anders vormgeven

**Comment by HermanAssink** [comment]
popup meer vrij stellen van de achtergrond, bijv door schaduwrand of dikker kader. In de Limburg variant komt de popup te ver naar rechts waardoor het kruisje buiten beeld raakt.

**Comment by AnkeVanBeek-IDgis** [comment]
begrippen worden in popup getoond (en kunnen weer gesloten worden)

**Comment by CoraPU** [comment]
lijkt mij prima.
