### ISSUE TITLE
hyperlink werkingsgebied

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#33]
Ook hier onduidelijk waar je naar toegaat als je op de hyperlink klikt. Maptip toevoegen. De link komt ook te laag uit de vetgedrukte kop behorende bij het gebied valt nog buiten beeld. 
![image](https://user-images.githubusercontent.com/30464824/200590142-a757121a-914f-4cea-b7c3-cfe2e1219273.png)

![image](https://user-images.githubusercontent.com/30464824/200590360-0666eaf7-77fe-4639-a55d-291e2188ab82.png)

Er zit wel een maptip (bekijk de inhoud van dit item)  bij het pictogram maar wat zegt dit ?  Dit is de knop zoom in naar locatie uit inhoudsopgave   dus zelfde maptip als uit inhoudsopgave hier opnemen ?

**Comment by CoraPU** [comment]
Link komt nu beter uit in de bijlage, alleen werkt de hoover dan niet op het item (is ook al een issue van Herman), als je via de link in de bijlage  terug gaat naar het artikel komt deze ook iets te laag uit titel van artikel staat niet in beeld 

Maptips zijn in orde zo

**Comment by copierrj** [comment]
De terug knop gaat op dit moment terug naar de link waarop eerder geklikt is. En dus niet naar het begin van het artikel waar de link in staat. 

Is dit iets wat aangepast dient te worden?

**Comment by CoraPU** [comment]
ja ik denk dat dat wel mooier is om naar het begin van het artikel of lid terug te gaan.

**Comment by CoraPU** [comment]
net besproken in ons wekelijks overleg met ZH en Limburg. Wens is om terug te gaan naar zelfde schermpositie vanwaar uit op de link is geklikt. Is dit technisch niet mogelijk dan naar begin van artikel

**Comment by copierrj** [comment]
Knop 'terug' springt nu naar het begin van het artikel.

**Comment by CoraPU** [comment]
lijkt goed te gaan springt bij lid terug naar begin lid en bij artikel naar begin artikel

**Comment by lamerise** [comment]
Bij ZH gaat dit niet altijd goed.. We hebben voornamelijk links naar bjilagen.. Als ik daar naar toe ben gesprongen kom ik soms niet goed meer terug naar de plek waar ik vandaan kwam, naar het artikel.

Lastig te reproduceren..

**Comment by HermanAssink** [comment]
Ik heb het ook getest en kan het niet reproduceren. Viewer gaat terug naar de plek die bij de Terug-knop wordt vermeld. Zullen we dit issue sluiten? Zo nodig maken we een nieuw issue aan als we een reproduceerbaar probleem zien.
