### ISSUE TITLE
venster zoek op kenmerken

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#34]
- op activiteiten tabblad hiërarchie toevoegen.   1x activiteit met daaronder gebod, verbod etc.
- ingestelde filters weergeven of aantal filters bv u zoekt nu op x aantal filters

**Comment by AnkeVanBeek-IDgis** [comment]
aantal ingestelde vensters is inmiddels zichtbaar.
hiërarchie in activiteiten volgt nog
