### ISSUE TITLE
layout, opmaak van tekst

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#35]
![opmaak](https://user-images.githubusercontent.com/30464824/201340535-f35918a7-2695-4dd7-ac69-a6bfb46d135b.png)

**Comment by copierrj** [comment]
Waargave van leden is verbeterd.

**Comment by lamerise** [comment]
Inspringing als er na een lijst volgt lijkt nog niet goed te gaan (Staat ook bij lid nummer #43

**Comment by CoraPU** [comment]
De layout is verbeterd en de opmerkingen zijn aangepast. Opmerking over leden zie dan issue 43
