### ISSUE TITLE
Hoover over locatie in bijlage 1 werkt wel/niet afhankelijk van scroll-positie

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#36]
In onderstaande screenshot stond de cursor boven de join-id van "Grondwaterbeschermingsgebied" zonder de locatie te highlighten in de kaart. Als "Grondwaterbeschermingsgebied" naar het midden van het venster wordt gescrolld dan wordt de locatie wel gehighlight, zie tweede screenshot.

![image](https://user-images.githubusercontent.com/2979044/202640625-d4195aac-b0cc-4cc8-ba88-80ec27c66b56.png)

![image](https://user-images.githubusercontent.com/2979044/202641473-1408ddc0-9adc-4a3f-85ec-4044dea22153.png)

**Comment by lamerise** [comment]
als ik over het vet gedrukte woord (kopje) van de gio ga, krijg ik een handje (lijkt dus een link) maar ik kan er niet op klikken.. Dat is verwarrend.

Hover over de /join/... gaat wel goed.. Alleen het icoontje er achter is klikbaar.

**Comment by lamerise** [comment]
is klaar wat mij betreft
