### ISSUE TITLE
Bij ‘annotaties’ worden alle soorten annotaties verzameld onder ‘gebiedsaanwijzing’?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#4]

**Comment by HermanAssink** [comment]
Dit venster wordt nog gevuld met voorbeeldgegevens. Vulling o.b.v. inhoud van het plan/omgevingsdocument (verordening, visie, etc) moet nog worden ontwikkeld.

**Comment by copierrj** [comment]
Het venster wordt in de laatste versie wel gevuld op basis van de inhoud van geopende documenten. Het daadwerkelijk selecteren van artikelen is nog niet gerealiseerd.

**Comment by lamerise** [comment]
Zit in andere issues #31
