### ISSUE TITLE
Witte balk ontstaat rechts naast tekst na schuiven (verkleinen) kaart links en rechts

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#40]
![image](https://user-images.githubusercontent.com/2979044/203921819-246115e6-445e-4a3a-b01b-c7225597e2c6.png)

**Comment by AnkeVanBeek-IDgis** [comment]
werkt weer zoals verwacht.

**Comment by TitiaBaeten** [comment]
opgelost
