### ISSUE TITLE
Na schuiven (vergroten) kaart links en rechts verdwijnt het deelvenster "tekst" buiten beeld en daarmee oon de knop "open tekst in los venster" (soms ook inhoudopgave)

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#41]
![image](https://user-images.githubusercontent.com/2979044/203922004-ab422273-a41a-4f74-8fe4-9e9520689f99.png)

**Comment by TitiaBaeten** [comment]
knoppen blijven nu in beeld na verschillende keren met de vensters geschoven te hebben
