### ISSUE TITLE
Bij het selecteren van de kaart vanuit deelvenster tekst schiet de inhouidsopgave naar links

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#42]
![image](https://user-images.githubusercontent.com/2979044/203922156-c71c5321-f241-4914-b124-00c937eb8490.png)

**Comment by lamerise** [comment]
Bij onze versie (ZH) ook. Het lijkt bij ons te starten/op te treden als je gaat schuiven om de breedte van de inhoudsopgave aan te passen.

**Comment by AnkeVanBeek-IDgis** [comment]
schuiven van de scheidingsbalken is inmiddels verbeterd.

**Comment by TitiaBaeten** [comment]
opgelost
