### ISSUE TITLE
In inhoudsopgave woordje "lid" toevoegen vóór lidnummer, in tekstvenster het lidnummer vóór de tekst van het lid zetten.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#43]

**Comment by copierrj** [comment]
Lidnummer staat al voor de tekst van het lid:

![image](https://user-images.githubusercontent.com/2194475/204012797-b84d25fd-820f-48fe-b74c-2278c372d867.png)

**Comment by HermanAssink** [comment]
In het tekstvenster moet het lidnummer dezelfde grootte hebben als de tekst van het lid, het nummer moet wel vet worden weergegeven. Het lidnummer lijkt ook lager te staan dan de tekst van het lid.

**Comment by lamerise** [comment]
Inspringing bij een lid als daaronder een lijst komt gaat niet goed.. Tekst komt te veel naar rechts te staan lijkt het.

![image](https://user-images.githubusercontent.com/114915209/208369156-04d851f3-655e-4358-a3f2-dcccb8c59a64.png)
