### ISSUE TITLE
Plaatjes worden horizontaal gesqueezed bij verkleinen tekstdeel (zie bijv. bijlage). Alternatief zowel hor. als vert. verkleinen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#44]

**Comment by copierrj** [comment]
De hoogte in de aangeleverde data is hier waarschijnlijk de boosdoener:
![image](https://user-images.githubusercontent.com/2194475/204015256-b4e0866d-ade7-49f2-9cc3-08fcb4229633.png)

**Comment by copierrj** [comment]
@KevinvdBosch is jou dit eerder ergens opgevallen?

**Comment by KevinvdBosch** [comment]
Nee, heb ik nog niet eerder gezien. Volgens [de documentatie](https://koop.gitlab.io/STOP/standaard/1.3.0/tekst_xsd_Attribute_Group_tekst_agInlineTekstAfbeelding.html#agInlineTekstAfbeelding) zijn de waarden bij de attributen hoogte en breedte in pixels en moeten die overeenkomen met de pixels in de afbeelding. Als hier vreemde waarden in voorkomen kan dit een bug in de plansoftware zijn

**Comment by copierrj** [comment]
Zowel hoogte als breedte matched niet met de afmeting van de png bestanden:
![image](https://user-images.githubusercontent.com/2194475/204018752-2e6a7fda-0de6-4c87-993d-79e95a6bf3d7.png)

**Comment by KevinvdBosch** [comment]
De DSO viewer lijkt zelf niets met de hoogte en breedte te doen:
![afbeelding](https://user-images.githubusercontent.com/27193836/204019127-e6ace6d8-2b98-434a-9440-01916e3b89fe.png)
![afbeelding](https://user-images.githubusercontent.com/27193836/204019169-d7e514bb-a4bc-4e79-942d-3b9ce0766924.png)

**Comment by copierrj** [comment]
@HermanAssink issue ergens melden of net als de DSO viewer de hoogte en breedte gewoon nergeren?

**Comment by HermanAssink** [comment]
Negeren

**Comment by copierrj** [comment]
Plaatjes in bijlagen Omgevingsverordening Limburg worden nu wel correct getoond. Onderliggende issue (= fout in data) leidt niet langer tot problemen in PlanoView.

**Comment by HermanAssink** [comment]
Bij Tercera navragen waarom er gekke waarden staan bij hoogte van de plaatjes.
