### ISSUE TITLE
Huisstijl wensen Zuid-Holland

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#46]
Evert-Jan zou graag wat willen met grid indeling van PZH (zie [www.zuid-holland.nl](http://www.zuid-holland.nl/))

Dus een kleine grijze/witte ruimte links en rechts de gekleurde blokjes..

Logo iets uit de zijkant.

Grijs lijntje er onder waaronder dan de functies etc kunnen komen.

Is zoiets te realiseren?

Zie ook

https://wapenfeiten.zuid-holland.nl/bouwstenen/grid/grid-voor-websites

https://wapenfeiten.zuid-holland.nl/toepassingen/online/vormgeving-websites

Neem even contact op met Evert-Jan voor uitwerking van de huisstijlwensen

**Comment by lamerise** [comment]
Graag zouden we nog iets zien om de maximale breedte van de viewer te beperken


Op de pzh website komen er grijze balken vanaf 1281 pixels breed 
Op een gegeven moment schakelt de site naar grotere DNA balk  en logo (vanaf 1440 pixels) en verschijnen bij bredere schermen ook weer

Conform de richtlijnen van de huisstijl zou er vanaf 1600 pixels breed naar een DNA balk op relatieve grote moeten worden geschakeld (1/20). Maar dat lijkt me heel complex worden..

Maar om dat te voorkomen zouden er grijze balken naast de viewer moeten komen.

Ik denk dan vanaf 1600px.


Verder ook nog even goed kijken naar het schaal moment voor kleinere schermen <768

Wat is bij planoview het schaalmoment naar mobiel?

**Comment by MaxIDgis** [comment]
Zie https://github.com/IDgis/PlanoView2-bevindingen/issues/125
