### ISSUE TITLE
Bij losgekoppeld tekstvenster moet de hint bij de knop "sluit tekstvenster" worden.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#47]
Zie ook #26

**Comment by copierrj** [comment]
De knop is niet langer zichtbaar op het losgekoppelde tekstvenster. Is dit de correcte oplossing of moet de knop terugkomen met aangepast gedrag en hinttekst?

**Comment by HermanAssink** [comment]
Het standaard kruisje voor het sluiten van een venster is voldoende m.i.

**Comment by HermanAssink** [comment]
Het losgekoppelde venster kan met het kruisje gesloten worden. Werkt tot tevredenheid.
