### ISSUE TITLE
(divisietekst)  te zien in inhoudsopgave

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#48]
![image](https://user-images.githubusercontent.com/114915209/203933092-9eb67933-8ebc-4b41-9326-235a44f84e95.png)

Is dit de bedoeling?

In de lopende tekst is er niet van te zien.. Zit er een structurerend element zonder kop/titel?

**Comment by copierrj** [comment]
Ja, deze Bijlagen bestaan uit twee structuurobjecten. Een divisie (met kop en zonder inhoud) met daarin een divisietekst (zonder kop maar met inhoud). We hebben er (voor nu) voor kozen om beide terug te laten komen in de inhoudsopgave omdat beide structuurobjecten annotaties kunnen hebben.

**Comment by lamerise** [comment]
als een divisietekst geen kop heeft en geen annotaties dan kunnen we hem weglaten.

**Comment by copierrj** [comment]
Is aangepast:
![image](https://user-images.githubusercontent.com/2194475/204824198-33b460f1-804c-4360-9271-abe2b67b5617.png)

**Comment by HermanAssink** [comment]
Tekst "(divisietekst)" weglaten als er alleen een annotatie aan de divisietekst is gekoppeld. Het structuurelement moet dus in dat geval blijven staan in de inhoudsopgave maar zonder de tekst "(divisietekst)".

Dit staat er in de standaard:

Het element [tekst:Kop](https://koop.gitlab.io/STOP/standaard/1.2.0/tekst_xsd_Element_tekst_Kop.html#Kop) is optioneel. Er zijn echter wel situaties waar een kop voor een Divisietekst wenselijk is:

wanneer een Divisietekst wordt voorzien van een juridische annotatie;
wanneer vanuit andere tekst aan de betreffende tekst wordt gerefereerd met een tekst:IntRef of tekst:ExtRef;
indien een Divisietekst als onderdeel opgenomen moet worden in een inhoudsopgave.

**Comment by HermanAssink** [comment]
We lopen met bovenstaande workaround tegen een probleem aan: Als met zoeken op een woord dit woord in een weggelaten  divisietekst wordt gevonden dan kan deze divisietekst niet gehighlight worden in de inhoudsopgave. Oplossing: Is "Inleiding" een beter kopje dan "(divisietekst)"?
Voor de duidelijkheid: Wat we er in de data zit is een divisiekop zonder divisietekst en vervolgens een divisietekst zonder divisie erboven.

**Comment by HermanAssink** [comment]
Volgens STOP is het mogelijk om binnen een divisie zowel een divisietekst als een divisie te maken, bijv:
### Paragraaf 1.2
Dit is inleidende tekst onder de paragraaf
#### Subparagraaf 1.2.1

**Comment by lamerise** [comment]
Maar het tekstje "Dit is inleidende tekst onder de paragraaf" moet toch altijd in een divisietekst zitten (en dat is een los object.) want in divisie kan geen tekst zitten toch..

Daardoor ontstaat het probleem...

En divisie met direct daaronder een divisie is dus alleen een structurerend element zonder tekst inhoud.. Dit mag inderdaad ook.. (maar speelt geen rol voor dit vraagstuk toch?)

**Comment by HermanAssink** [comment]
Wat ik met bovenstaand voorbeeld wil zeggen is dat de standaard niet belemmerend is om onder een divisie een divisietekst op te nemen en binnen de eerste divisie, op het zelfde niveau als de divisietekst, een divisie op te nemen. De oorzaak van het moeten weergeven van een label als (divisietekst) is dat er een divistekst is opgenomen zonder direct bovenliggende divisie. Zoals hieronder:

- A.1. Schadelijke stoffen, mengsels, materialen en producten, bedoeld in artikel 3.22 (divisie)
--[leeg] (divisietekst)
- [leeg] (divisie)
-- Als stoffen, mengsels, materialen en producten schadelijk voor de kwaliteit van het grondwater als bedoeld in artikel 3.22... (divisietekst )

Het probleem is dus oplosbaar door de inhoud anders op te bouwen, namelijk de divistekst direct onder de divisie opnemen en niet in een aparte divisie zonder koptekst. Ik stel daarom voor het label "(divisietekst)" te vervangen door het label "tekst". De term divisietekst zegt namelijk alleen iets voor mensen die bekend zijn met STOP.

**Comment by HermanAssink** [comment]
I.p.v. "(divisietekst)",  "(tekst zonder kop)" als tekst voor het structuurelement opnemen
