### ISSUE TITLE
kruimelpad loopt niet mee met tekst 

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#49]
kruimelpad loopt niet mee bv als je bij artikel 2.45 naar beneden scrolt worden artikel (2.46) overgeslagen (omgevingsverordening)
![image](https://user-images.githubusercontent.com/30464824/203934446-718ba36d-5faa-4afe-85bb-d02593f16f3b.png)

**Comment by TitiaBaeten** [comment]
![image](https://user-images.githubusercontent.com/119037891/203934625-be10dcdf-a385-4951-b6fd-cc43ca255cf7.png)

Kruimelpad geeft al 4.13 lid aan terwijl deze nog niet in beeld is

**Comment by lamerise** [comment]
werkt nu goed
