### ISSUE TITLE
Lijsten moeten conform standaard/STOP-xml worden geletterd/genummerd

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#50]
Hieronder een voorbeeld waar het fout is. Blijkbaar kun je nu in de STOP-xml afwijken van de standaard. Voorkeur heeft om de typering van de nummering in de STOP-xml te volgen.

![image](https://user-images.githubusercontent.com/2979044/205245356-30187f26-58e9-441c-8840-05265e2650fb.png)

**Comment by lamerise** [comment]
1 met een rondje erachter etc. lijstjes werken nog niet

DSO:
![image](https://user-images.githubusercontent.com/114915209/208369893-41ca8a4a-bb61-4994-a3c8-7583822bdb8e.png)

Planoview:
![image](https://user-images.githubusercontent.com/114915209/208369910-9d532287-1a0e-47d0-a70d-3ced5c6ad0e1.png)

**Comment by CoraPU** [comment]
bij artikel 6.15 verschil in opsommingsteken onder a en b.  Of is dit op de verschillende manieren ingevoerd in tercera 
![image](https://user-images.githubusercontent.com/30464824/208072440-e6217385-b225-46c9-92bf-a2b1618223aa.png)

**Comment by HermanAssink** [comment]
Het voorbeeld van Evert Jan wordt nu goed weergegeven, maar dat van Cora niet. In de STOP.xml is de sublijst onder b. doorgenummerd t.o.v. de sublijst onder a. Mag dit volgens STOP?
![image](https://user-images.githubusercontent.com/2979044/209289595-74402175-f93e-4e88-a62a-ccea0fe1a16b.png)

**Comment by copierrj** [comment]
CC: @KevinvdBosch

**Comment by lamerise** [comment]
ik weet dat het volgens mij niet de bedoeling is van utrecht is om dit zo te doen, maar het komt zo wel uit de tercera editor... Ik zag laatst een test wijzigbesluit van utrecht waarin dit soort dingen hebben aangepast...

**Comment by HermanAssink** [comment]
Nummering ziet er nu goed uit. Ook vastgesteld door Utrecht
