### ISSUE TITLE
Standaard gebiedsaanwijzingen aanzetten in het kaartbeeld bij aanzetten van het structuurelement.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#51]

**Comment by lamerise** [comment]
Ik twijfel nu of het higlighten als je er over HET HELE ARTIKEL gaat met je muis (erbij) dan wel handig is... Nu ik het zo zie zou ik dit liever niet zo prominent zien of zelfs willen weglaten

**Comment by CoraPU** [comment]
dit lijkt nog niet helemaal goed te gaan. als ik bv heel hfdst 6 aanvink in onze verordening. Dan zouden de gebiedsaanwijzingen onder bv artikel 6.1  allemaal aan moeten staan in het kaartbeeld want de schuifjes staan aan . Zowel NNN en Groene contour worden niet getoond en van de Weidevogelkerngebieden wordt maar een deel getoond 
![image](https://user-images.githubusercontent.com/30464824/208068170-b9af0efc-8e34-4430-b36e-591099daa8ec.png)

Als je de schuifjes een keer aan/uit zet onder 6.1 dan is het kaartbeeld correct 
![image](https://user-images.githubusercontent.com/30464824/208068808-dc149bb5-08aa-4a8d-9513-7948c1089fc1.png)

**Comment by HermanAssink** [comment]
@lamerise: Wat moet er worden aangezet als het betreffende structuurelement geen gebiedsaanwijzing-annotatie heeft?

**Comment by copierrj** [comment]
De boosdoener is hier waarschijnlijk de tekenvolgorde. Bij het weergeven van alle gebiedsaanwijzingen in hoofdstuk 6 (en dit zijn er nogal wat) wordt een willekeurige tekenvolgorde gebruikt waardoor de kans groot is dat bepaalde gebiedsaanwijzingen gemaskeerd worden door een andere gebiedsaanwijzing op dezelfde locatie.

**Comment by lamerise** [comment]
@HermanAssink: ik denk dat er met de huidige keuze om gebiedsaanwijzingen aan te zetten niks aangezet hoeft te worden als er geen gebiedsaanwijzing is (denk ik nu)... Daarbij zou het uitgangspunt moeten zijn dat waar je wat op de kaart wil zien altijd voorzien zou moeten zijn van een gebiedsaanwijzing...

Er zijn ook interpretaties van het gebruik van gebiedsaanwijzing denkbaar waar alleen het artikel waar het gebied ook daadwerkelijk wordt aangewezen een gebiedsaanwijzing is.. Dan zou het wat magertjes uitpakken in de viewer...(want staat er niet zo veel aan)

**Comment by CoraPU** [comment]
voor nu ok
