### ISSUE TITLE
traag en vastlopen

### ISSUE THREAD

**Issue by CoraPU** [IDgis/PlanoView2-bevindingen#53]
Ik heb nu ook problemen met traagheid en het vastlopen 

Als ik de hele visie aan heb staan dan hapert het scrollen door de tekst/inhoudsopgave en soms loopt het helemaal vast en krijg ik de volgende melding

![image](https://user-images.githubusercontent.com/30464824/208075236-deb25a87-5377-4f1a-b9ba-1463ee72630d.png)

**Comment by copierrj** [comment]
De applicatie is aangepast waardoor het geheugengebruik niet langer ongebreideld groeit. Hopelijk zijn de traagheid en de vastlopers hiermee verleden tijd.

**Comment by HermanAssink** [comment]
Bevinding Cora: Viewer blijft hangen nadat zowel visie en verordening waren geopend en vervolgens een van beide werd gesloten

**Comment by copierrj** [comment]
> Bevinding Cora: Viewer blijft hangen nadat zowel visie en verordening waren geopend en vervolgens een van beide werd gesloten

Het is mij niet gelukt dit te reproduceren.

**Comment by HermanAssink** [comment]
Gesloten omdat het te reproduceren is.
