### ISSUE TITLE
Voor highlight in kaartbeeld bij hoover over artikel/lid een vertraging in bouwen.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#56]
Als je met de muis over inhoudsopgave beweegt is het kaartbeeld onrustig doordat allerlei gebieden opflitsen. Daarom de highlight pas laten zien als de muis even stilstaat boven een artikel/lid.

**Comment by copierrj** [comment]
Is de suggestie in #65 wellicht een alternatief tegen de onrustige highlight functie?

**Comment by copierrj** [comment]
We hebben proefondervindelijk vastgesteld dat het vertragen van de highlight 'vreemd' aanvoelt. Daarom voor nu eerst de oplossingsrichting in #65 geïmplementeerd zodat hiermee getest kan worden.

**Comment by copierrj** [comment]
Kan dit issue (nu #65 aan de verwachtingen lijkt te voldoen) gesloten worden?

**Comment by HermanAssink** [comment]
Ja
