### ISSUE TITLE
Bij zoeken inhoudsopgave scrollen naar eerste gehighlighte structuurelement, zoals bij aanzetten van gevonden structuurelementen.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#60]
Zonder de automatische scroll moet de gebruiker zelf zoeken in de inhoudsopgave

**Comment by HermanAssink** [comment]
Bij klik in de kaart scrollt de inhoudsopgave zo te zien naar een willekeurige positie

**Comment by copierrj** [comment]
> Bij klik in de kaart scrollt de inhoudsopgave zo te zien naar een willekeurige positie

is aangepast

**Comment by HermanAssink** [comment]
Werkt goed.
