### ISSUE TITLE
Zoekingangen in volgorde van belangrijkheid: locatie, tekst, kenmerken

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#62]
Het zoeken op kenmerken is een geavanceerde vorm van zoeken. Om die reden moet deze onderaan staan. Zoeken via klik in de kaart / adres is het meest gebruikt. Daarom moet deze bovenaan.

**Comment by HermanAssink** [comment]
Zoekopties staan nu in de goede volgorde: locatie, tekst, kenmerken

**Comment by lamerise** [comment]
geimplementeerd.. Kijken of dit logisch is en/of bevalt
