### ISSUE TITLE
I.p.v. locaties het werkingsgebied aan/uit kunnen zetten bij annotaties

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#64]
Het aan/uit kunnen zetten van locaties heeft geen toegevoegde waarde t.o.v. het aan/uit zetten van de annotaties. Daarom i.p.v. de locaties de mogelijkheid bieden het werkingsgebied aan/uit te zetten.

N.B. Het kunnen zoeken op locaties bij zoeken op kenmerken wordt handig gezien en moet dus mogelijk blijven.

**Comment by copierrj** [comment]
Dit lijkt in conflict met #31

**Comment by HermanAssink** [comment]
Eerst testen of de implementatie van #31 naar tevredenheid werkt.

**Comment by HermanAssink** [comment]
#31 werkt tot tevredenheid, deze kan dus ook gesloten worden
