### ISSUE TITLE
Bij scrollen in tekstvenster loopt de inhoudsopgave niet goed mee

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#67]
De inhoudsopgave loopt  wel mee bij het scrollen in het tekstvenster maar laat vaak andere artikelen zien dan zichtbaar zijn in het tekstvenster

**Comment by copierrj** [comment]
Kun je een voorbeeld geven van een document + locatie waar dit veelvuldig voorkomt?
