### ISSUE TITLE
Bovenste balk neemt veel ruimte in

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#71]
Bovenste balk neemt  veel ruimte in. Suggestie om deze balk minder hoog te maken, en te benutten voor bedieningsfuncties die daar logisch zijn (printen, delen, contact, help) .

**Comment by HermanAssink** [comment]
Suggestie: Titelbalk laten vervallen en logo zwevend boven het kaartbeeld zetten
