### ISSUE TITLE
Tekstvoorstel uitleg documentselectie

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#73]
Tekstvoorstel uitleg documentselectie: “Wanneer je op een document klikt, maar niet op de checkbox, sluit je de pop-up na het openen van het document. Wanneer je op de checkbox klikt wordt de pop-up niet gesloten en kun je meerdere documenten aanvinken.” Vervangen door “Vink documenten aan en sluit de pop-up (x) of klik op documentnaam om direct het betreffende document te openen.”

**Comment by HermanAssink** [comment]
Wordt o.a. opgelost door toelichting per site weer te geven
