### ISSUE TITLE
Inhoudsopgave: aanvinken checkbox

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#74]
Aanvinken checkbox: vinkje verschijnt pas als kaart en inhoudsopgave zijn geladen. Zou duidelijker zijn als het vinkje wel al direct zichtbaar is, of er een zandlopertje loopt, nu twijfel ik of ik wel goed geklikt heb.

**Comment by HermanAssink** [comment]
Vinkje is vervallen door nieuwe look
