### ISSUE TITLE
Inhoudsopgave: schuifregelaar lay-out

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#75]
Schuifregelaar is erg “uitgerekt”, wellicht ook logischer om checkbox te gebruiken?

**Comment by HermanAssink** [comment]
Lengte van schuifregelaar terugbrengen naar ca 2/3 van de huidige lengte.

**Comment by HermanAssink** [comment]
Ziet er nu goed uit.
