### ISSUE TITLE
Leesvenster: bij hoover "Link naar begrip" popup tonen

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#77]
Hoover over “Link naar locatie” levert highlight in kaart op. Hoover over “Link naar begrip” alleen de tooltip. Overweging: de pop-up tonen (automatisch openen en sluiten bij hoover).

**Comment by HermanAssink** [comment]
Automatisch openen van popup met begrip wordt te onrustig, denk ik

**Comment by HermanAssink** [comment]
Werkt naar wens
