### ISSUE TITLE
Na selecteren van plannen en daarna deselecteren van plannen blijft een oud kaartbeeld achter

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#78]
Na selecteren van plannen en daarna deselecteren van plannen blijft een oud kaartbeeld achter. Getest met https://utrecht.viewer.planoview2-demo.idgis.eu/:
<img width="946" alt="planoview-testbevinding-1" src="https://user-images.githubusercontent.com/10918902/211000661-5a120038-d642-4abf-beb3-8a19e8c9115a.png">

**Comment by HermanAssink** [comment]
Werkt nu goed
