### ISSUE TITLE
Inhoudsopgave: bij highlight items onderscheid in knoppen  visualiseren

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#79]
Bij hoveren over inhoud wordt “inhoudsitem inclusief iconen gehighlight”. Terwijl het drie verschillende clickable items zijn: het betreffende item, de kenmerken en de zoom naar locatie. Wellicht duidelijker om die driedeling ook te visualiseren in de highlight. 
<img width="147" alt="planoview-testbevinding-2" src="https://user-images.githubusercontent.com/10918902/211004633-6bfae2cd-5f21-49ba-8bfa-09c8cced31c1.png">
<img width="170" alt="planoview-testbevinding-2a" src="https://user-images.githubusercontent.com/10918902/211004635-3ab14f32-bc7b-4bcf-860a-33fff475803b.png">

**Comment by HermanAssink** [comment]
Knoppen worden nu afzonderlijk van het opschrift van artikel/lid gehighlight bij hooveren
