### ISSUE TITLE
Navigatietabblad aan de linkerkant mee laten scrollen met de tekst aan de rechterkant

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#8]

**Comment by CoraPU** [comment]
lijkt goed te gaan

**Comment by HermanAssink** [comment]
Nu verspringt soms de inhoudsopgave als er in de inhoudsopgave structuurelementen aa/uit worden gezet. Dat is onwenselijk. De wens is dat de inhoudsopgave alleen verspringt als de tekst in het tekstvenster handmatig/door de gebruiker verschoven wordt.

**Comment by lamerise** [comment]
Ik stoor me hier nu niet (meer) aan.. Dit lijkt wel prettig te werken
