### ISSUE TITLE
Bij “openen tekst in los leesvenster” wordt de tekst vanaf het begin weergegeven

### ISSUE THREAD

**Issue by kraaka** [IDgis/PlanoView2-bevindingen#80]
Bij “openen tekst in los leesvenster”, bijvoorbeeld na scrollen en lezen in het hele document wordt de tekst in het losse beeldscherm  vanaf het begin weergegeven en niet het gedeelte waar ik op dat moment aan het lezen was met bijbehorende kaartbeeld.

**Comment by MaxIDgis** [comment]
Geen prioriteit
