### ISSUE TITLE
Inhoudsopgave breder maken bij openen viewer/document

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#82]
Inhoudsopgave is nu te smal om tekst goed te kunnen lezen. 25% van de breedte van het scherm voor de inhoudsopgave lijkt een goede waarde.

**Comment by CoraPU** [comment]
Is de inhoudsopgave breder nu ? ik heb het idee dat het niet veranderd is

**Comment by HermanAssink** [comment]
Lijkt voor nu OK, misschien later na meer ervaring de breedte nog aanpassen
