### ISSUE TITLE
Meten lijn/polygoon in kaart: toevoegen tooltip voor sluiten functie 

### ISSUE THREAD

**Issue by AnkeVanBeek-IDgis** [IDgis/PlanoView2-bevindingen#89]
dubbelklik voor stoppen met meten, nogmaals klik **op knop** voor sluiten functionaliteit

**Comment by HermanAssink** [comment]
@TitiaBaeten: Wat was de reden om het label "getest met bevindingen" toe te kennen?

**Comment by HermanAssink** [comment]
Tooltip maakt m.i. duidelijk dat er nogmaals geklikt moet worden om het meten af te sluiten
