### ISSUE TITLE
Titel(s) van gekozen regeling(en) tonen in titelbalk

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#9]

**Comment by CoraPU** [comment]
titels worden nog niet getoond in titelbalk

**Comment by CoraPU** [comment]
titels worden wel getoond maar valt niet op.  witte tekst of vet gedrukt valt misschien meer op

**Comment by HermanAssink** [comment]
Zie PlanoView1

**Comment by HermanAssink** [comment]
Er is besloten om de titel(s) van geselecteerd(e) document(en) alleen boven de inhoudsopgave weer te geven en niet in de titelbalk.
