### ISSUE TITLE
Huisstijl ZH: Karbon als font wel opgegeven maar niet bijgevoegd

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#90]
Opm ZH: Ze hebben het font wel aangeroepen, maar niet ingeladen. Dus ze hebben wel gezegd het moet 'Karbon' zijn, maar het hele lettertype is niet bijgevoegd. Dus iemand die de website bekijkt op een computer of apparaat waar geen Karbon geïnstalleerd staat (en dat zijn de meeste apparaten), dan zien ze niet het juiste font, maar Times New Roman. 

Het rare/ouderwetse font viel me ook al op. Ik begrijp nu waar dat vandaan komt. Kan dit goed ingeregeld worden?  Of zou iig het terugval font niet Times New Roman kunnen zijn, maar een ander iets strakker font.

**Comment by copierrj** [comment]
Het is in principe mogelijk om een web font te gebruiken. Dan hoeft het font niet langer op de computer van de gebruiker geïnstalleerd te zijn.

Karbon is echter een proprietary font. Hoewel het gebruik van Karbon als web font is toegestaan zijn hier (complicerende) voorwaarden aan verbonden.

Een alternatief zou kunnen zijn om een lookalike font te gebruiken. Dit zou bijvoorbeeld een font uit de [Google Font library](https://fonts.google.com/) kunnen zijn.

**Comment by lamerise** [comment]
Als terugval optie graag Calibri gebruiken, en anders de "stijl" Sans serif
