### ISSUE TITLE
ipad: resizen vensters met touch screen lukt niet.

### ISSUE THREAD

**Issue by AnkeVanBeek-IDgis** [IDgis/PlanoView2-bevindingen#95]

**Comment by HermanAssink** [comment]
@AnkeVanBeek-IDgis : Zullen wij tweeën samen de tablet issues testen? Provincies komen er niet aan toe.

**Comment by AnkeVanBeek-IDgis** [comment]
resizen via slepen van de balk(en) werkt zoals verwacht
