### ISSUE TITLE
Zoeken op adres

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/PlanoView2-bevindingen#96]

**Comment by CoraPU** [comment]
grijs van percelen mag meer transparanter, zwarte lijnen iets dunner

**Comment by TitiaBaeten** [comment]
bij klik op de kaart graag feedback van coordinaten of adres

**Comment by HermanAssink** [comment]
Feedback van coördinaat in het zoekveld is bij nader inzien niet nodig, marker in het kaartbeeld is voldoende.
