### ISSUE TITLE
Adres/locatie zoeken buiten de provinciegrenzen?

### ISSUE THREAD

**Issue by lamerise** [IDgis/PlanoView2-bevindingen#97]
Willen we dit of willen we dit beperken per provincie?

**Comment by HermanAssink** [comment]
Ja, beperken tot provincie c.q. ambtsgebied van de klantorganisatie. @copierrj : Biedt de PDOK-locatieserver deze mogelijkheid?

**Comment by HermanAssink** [comment]
@copierrj Welke mogelijkheden biedt de PDOK Locatieserver wat dit betreft

**Comment by copierrj** [comment]
Wellicht kunnen we filteren op  gemeente code. Ga ik uitzoeken.

**Comment by copierrj** [comment]
Het blijkt eenvoudig mogelijk om aanvullende zoekcriteria mee te geven aan de locatieserver waaronder filteren op provinciecode of gemeentecode.

**Comment by lamerise** [comment]
Als het ook makkelijk te implementeren is dan mag dat van mij

**Comment by HermanAssink** [comment]
Bij iedere provincie worden alleen adressen gevonden in die provincie. De provincie of gemeente waarbinnen gezocht moet worden is door IDgis per site instelbaar.

**Comment by Brtvrlndn** [comment]
werkt prima!

**Comment by HermanAssink** [comment]
Werkt ook goed voor Zuid-Holland en Utrecht, daarom gesloten.
